clojure-emacs/cider-nrepl

src/cider/nrepl/middleware/info.clj
test/cider/nrepl/middleware/info_test.clj

Try the following 
```clojure
(defn tt []
(/ 1 0))
(tt)
```
In the stacktrace go to the line for anonymous method ending in /evalNNN and jump to source. You should get a stacktrace in the message buffer similar to the following:
```
edebug-signal: Source has changed - reevaluate definition of cider--jump-to-loc-from-info
java.lang.NullPointerException: null
at java.util.concurrent.ConcurrentHashMap.hash (ConcurrentHashMap.java:333)
java.util.concurrent.ConcurrentHashMap.get (ConcurrentHashMap.java:988)
clojure.lang.Namespace.find (Namespace.java:188)
clojure.core$find_ns.invoke (core.clj:3728)
cider.nrepl.middleware.info$info_clj.invoke (info.clj:113)
cider.nrepl.middleware.info$info.invoke (info.clj:132)
cider.nrepl.middleware.info$info_reply.invoke (info.clj:217) …
```

Don't invoke `info-clj` on missing symbol

---

README.md
project.clj
src/cider/nrepl.clj
src/cider/nrepl/middleware/pprint.clj
test/cider/nrepl/middleware/pprint_test.clj

This adds a `wrap-pprint` middleware so that CIDER's pprinting functionality will also be ClojureScript-compatible. By using `interruptible-eval`'s optional `:eval` slot we can ensure that `clojure.core/pprint` is not evaluated in a CLJS context, and also keep the evaluation inside `interruptible-eval`'s machinery, so the user can interrupt the printing of the result at the REPL.
See also clojure-emacs/cider#972.

Add pprint middleware

---

src/cider/nrepl/middleware/util/misc.clj
test/cider/nrepl/middleware/util/misc_test.clj

It seems like `[]` was being passed in the `:ns` slot from the backtrace posted in clojure-emacs/cider#879. No idea why the client was doing that, but we shouldn't throw in that case.
The only valid types to pass to `symbol` are strings and symbols - since it either returns the symbol you passed, or calls `clojure.lang.Symbol/intern`, which takes a string.

Fix as-sym to not throw

---

src/cider/nrepl/middleware/info.clj
src/cider/nrepl/middleware/util/java/parser.clj

Not sure the best way to add tests for these without adding `funnyqt` to the test profile deps (since I'm not sure what it's doing to the classpath, and how else to replicate it). Will go ahead with that if you think it's needed.

Handle classpath-related errors in info middleware

---

src/cider/nrepl/middleware/pprint.clj

Whoops :blush:.
Found using Eastwood btw, I'm going through the [rest of the errors](https://gist.github.com/cichli/13bccd2cb3fcd89b0124) now. Might be useful to add this to Travis once they're all fixed so we don't introduce any more?

Fix misplaced docstring

---

test/cider/nrepl/middleware/info_test.clj

`test-info` is already defined earlier in the file, which triggers a warning in Eastwood. We could also just extract the eldoc tests into their own file.

Fix a redef'd var in info tests

---

src/cider/nrepl/middleware/util/java/parser.clj

Because `chars` is the name of a var in core, binding something to the name `chars` and then calling it directly as a function triggers an Eastwood warning. We could also rename `chars` to `char-map` or somesuch.

Fix an eastwood warning

---

src/cider/nrepl/middleware/complete.clj

Required by clojure-emacs/cider#993.
The 1.7.0-SNAPSHOT builds still seem to be unavailable but I can confirm locally that it builds and tests pass against 1.7.0-alpha5.

Update complete op to return annotated candidates

---

project.clj

This fixes cljs completion on 0.9.0-SNAPSHOT / latest CIDER. I still haven't sorted the Travis issue but received confirmation on the mailing list that it should be working - I think we should just use alpha5 instead of master until I get this figured out.

Bump cljs-tooling dep to 0.1.5-SNAPSHOT

---

src/cider/nrepl/middleware/inspect.clj
src/cider/nrepl/middleware/util/inspect.clj
test/cider/nrepl/middleware/inspect_test.clj
test/cider/nrepl/middleware/pprint_test.clj
test/cider/nrepl/middleware/test_session.clj

see clojure-emacs/cider#1009
* The magic around inspecting vars is now gone. It's possible to inspect either `map` or `#'map` depending on if you want to inspect the function itself or the var.
* Inspector state now lives in the session bindings map rather than a global atom.
* I've removed the reset op for now as the client was not using it. Easy to add it back in, which I will do in a separate PR when I add support to the client.
* We no longer serialise the result, as `pr-values` is now doing it for us.

Portable inspector

---

test/cider/nrepl/middleware/inspect_test.clj
test/cider/nrepl/middleware/pprint_test.clj
test/cider/nrepl/middleware/test_session.clj

Both `wrap-inspect` and `wrap-pprint` rely on the eval op, and I think it would be nice to have the tests catch any unexpected interactions between them (and likewise for any other handlers, existing or future).

Use default handlers in session fixture

---

project.clj

Changelog is [here](https://github.com/clojure/tools.namespace#change-log).
AFAICT this is only used by inlined code in the client, but moving to middleware would be useful. A potential `refresh` op could have the optional args:
* `before` - fully-qualified name of a function to run before refreshing
* `after` - fully-qualified name of a function to pass as the `:after` option to `refresh`
edit: ah just noticed #13 :-).

Bump tools.namespace dep to 0.2.10

---

.travis.yml
README.md
project.clj

I thought this was pretty cool - see what the reports look like [here](https://coveralls.io/r/cichli/cider-nrepl) or for a specific file [here](https://coveralls.io/files/527870364). It doesn't support partial line coverage (see lemurheavy/coveralls-public#216) so cloverage uses 1x line hit for partial coverage and 2x line hits for complete coverage.
PRs will have an extra status added with information on how test coverage has changed if you enable coveralls for the repo at http://coveralls.io (only needs status API permissions).

Send test coverage data to coveralls.io

---

README.md
project.clj
src/cider/nrepl.clj
src/cider/nrepl/middleware/debug.clj
src/cider/nrepl/middleware/util/instrument.clj
test/cider/nrepl/middleware/util/instrument_test.clj

This goes with clojure-emacs/cider#1019.
An edebug-like debugger for cider. You can:
1. step through the code,
2. quit execution, 
3. and inject values.
1. Do the usual`M-x cider-jackin`, but make sure you're using clojure >= 1.6. For instance,
(setq cider-lein-parameters "with-profile +1.6 repl :headless")
2. Call `M-x cider-debug-defun-at-point` with point inside a top-level sexp.
For a regular sexp this will immediately start debugging. If the top-level sexp was a `defn`, it will start debugging when you run the function.
Once you're in the debugger you can hit:
- **n**: next step
- **c**: continue execution
- **i**: inject value
- keybind and menu-bar entry.
- **e** key to evaluate an expression in the current scope.
- **q** key to completely quit execution.
- **o** key to “out” a …

Debugging in Cider

---

src/cider/nrepl/middleware/debug.clj
src/cider/nrepl/middleware/util/instrument.clj
test/cider/nrepl/middleware/util/instrument_test.clj

Amonst other things, this addresses the issues on raised on #170 with `do` and `recur`.

Some improvements to intrument.clj

---

project.clj
src/cider/nrepl/middleware/complete.clj
src/cider/nrepl/middleware/info.clj
src/cider/nrepl/middleware/inspect.clj
src/cider/nrepl/middleware/ns.clj
src/cider/nrepl/middleware/pprint.clj
src/cider/nrepl/middleware/stacktrace.clj
src/cider/nrepl/middleware/util/cljs.clj
test/cider/nrepl/middleware/pprint_test.clj

**Please do not merge yet.**
This PR is for adding support to the [0.2.0-SNAPSHOT branch](https://github.com/cemerick/piggieback/compare/new-cljs-repl) of piggieback, in a backwards-compatible way.

Piggieback 0.2.x support

---

src/cider/nrepl/middleware/debug.clj
test/cider/nrepl/middleware/debug_test.clj

While debugging something else I noticed a bug in the debugger.
If the user hits `c` to continue without stopping, clj-debugger's `break` statements don't trigger anymore (as expected) but we were still sending the debugger message for cider to "prepare" for a break.
This fixes that.

Don't send debugger message if the break won't prompt

---

project.clj

This prevents a version conflict that breaks latest CLJS.

Bump tools.reader dep to 0.9.1

---

project.clj

CLJS is still a somewhat fast moving target, I think for now we should test against latest rather than relying on the version piggieback provides. Please merge after #189, or the tests will not pass :-).

Test against latest ClojureScript version

---

.travis.yml
README.md
build.sh
project.clj
src/cider_nrepl/plugin.clj

- use mranderson to inline dependencies at package time
- simple build script to help working with mranderson
- bit of explanation in readme
- travis file modified accordingly
tests pass, not yet tested the built middleware tho (will do) but ready for a review I suppose.

[Fix #143] Inline dependencies

---

README.md

This fixes the section about working with a container that uses JBoss
modules - the issue actually *doesn't* affect Immutant users.

Update 'With Immutant/WildFly' section

---

test/common/cider/nrepl/test_session.clj

The unsupported op test will hopefully stabilise the test coverage reports by ensuring the `(handler msg)` branch is always called for all middlewares (currently it seems to depend on how nREPL orders them which is not deterministic).

Add test for session fixture

---

README.md
project.clj
src/cider/nrepl/middleware/debug.clj
src/cider/nrepl/middleware/util/instrument.clj
test/clj/cider/nrepl/middleware/debug_test.clj

- Rewrite the debugger to do most of the logic on the clojure side. Now, it only contacts cider.el when user input is needed.
- New commands beyond the previous ones: `quit`, `out`, `eval`.
- Much more documentation (which is why the line counts look so large).
I'll push the cider.el side of this later today, but I wanted to get this PR open because the code is pretty independent of cider.el.
Happy reading. This goes with clojure-emacs/cider#1085

Debugger rewrite

---

README.md
project.clj
src/cider/nrepl.clj
src/cider/nrepl/middleware/refresh.clj

This just delegates to the `eval` op, similar to nREPL's own `load-file`. Unfortunately it's tricky to call `refresh` directly from the middleware since it sets `*e`, which doesn't play well with nREPL's binding conveyance. Seeing as how `load-file` also sets `*e` and `*1` I think it's acceptable for this middleware to do it too.
The `msg` arg to `refresh-code` is unused as of now, but I plan to add `after`/`before` options to make the reloaded workflow easier to integrate in CIDER - I'm just not sure how this will work client-side. I guess we can prompt for the namespace-qualified symbols of the functions to call before/after refreshing, or have options for them and encourage people to use `.dir-locals.el` to set them on a per-project basis.
Fixes #13.

Add refresh middleware

---

src/cider/nrepl/middleware/util/instrument.clj
test/clj/cider/nrepl/middleware/util/instrument_test.clj

Defines a new function instrument-function-call, which is like instrument-coll, except the first element is not instrumented.
This is only used if the first element is a symbol.

[Fix cider#1089] Don't instrument symbol in call position

---

src/cider/nrepl/middleware/pprint.clj

For CCW I make use of the `describe` op to discover available middlewares.
The proposed change would enable `pprint` to be discovered like any other middleware.

Give a middleware name for pprint so it can be discovered dynamically

---

README.md
src/cider/nrepl/middleware/ns.clj
test/clj/cider/nrepl/middleware/ns_test.clj

This op returns the file path to the file containing some ns on classpath.
The new op is meant to be the basis for cider-find-ns

Add ns-path op

---

src/cider/nrepl/middleware/pprint.clj
test/clj/cider/nrepl/middleware/pprint_test.clj
test/cljs/cider/nrepl/middleware/cljs_pprint_test.clj
test/common/cider/nrepl/test_session.clj

* The printed result is now streamed via the `:pprint-out` slot
* After each result is printed, a response is sent with a non-nil value in the `:pprint-sentinel` slot
* The `:value` slot is now elided from responses
Fixes #200.
Not including the `:value` slot means the client won't choke trying to decode or print it all at once. The client changes aren't ready yet, but I'm posting this for review + so @laurentpetit can be ready for if/when this merges.
Thoughts? Eventually on the client we'll be able to use this to prevent the interleaving of evaluation results and things written to `*out*` - either by sending them to different buffers, or queuing the `*out*` responses while an evaluation result is being printed.

Update pprint middleware to not hijack *out*

---

project.clj
src/cider/nrepl/middleware/complete.clj
test/clj/cider/nrepl/middleware/complete_test.clj
test/cljs/cider/nrepl/middleware/cljs_complete_test.clj

Fixes #176 
Merged: alexander-yakushev/compliment#26
Merged: gtrak/cljs-tooling/pull/18
Merged: gtrak/cljs-tooling/pull/19
@bbatsov In relation to alexander-yakushev/compliment#26
I decided to open this PR here for comments even though PR to Compliment is not merged yet and cljs-tooling doesn't have the support for options yet. 
Added options which allow frontends to request arglists and doc for each completion results. Passes the options to Compliment.

Add extra-metadata options to complete middleware

---

src/cider/nrepl/middleware/debug.clj
src/cider/nrepl/middleware/util/instrument.clj
test/clj/cider/nrepl/middleware/util/instrument_test.clj

instrument.clj: Add support for `proxy`, `or`, and `and`

---

src/cider/nrepl/middleware/info.clj

Fixes instances where cljx files have the same name as directories in the classpath.

don't attempt to read file paths unless they are actually files.

---

src/cider/nrepl/middleware/util/java/parser.clj

This PR is related to #210.
That change causes weird behavior in my environment.
If "ja_JP" (my default locale)  is passed to DocEnv/setLocale, the default locale will be overwritten to "ja_JP_JP_#u-ca-japanese".
When new locale is passed to DocEnv/setLocale again, it becomes the error. 
I've read source code of com.sun.tools.javadoc.DocLocale and found that `getLocale` method returns the default locale itself when passed locale name is empty string.
```clj
user=> (require 'cider.nrepl.middleware.util.java.parser)
nil
user=> (in-ns 'cider.nrepl.middleware.util.java.parser)
#<Namespace cider.nrepl.middleware.util.java.parser>
cider.nrepl.middleware.util.java.parser=> (def docenv (let [access   (ModifierFilter. ModifierFilter/ALL_ACCESS)
#_=>                   context  (doto (Context.) …
```

Avoid overwriting default locale

---

src/cider/nrepl/middleware/apropos.clj
src/cider/nrepl/middleware/ns.clj
test/clj/cider/nrepl/middleware/ns_test.clj

Our own inlined deps, created by mranderson, as well as the inlined deps
from eastwood were polluting the result of the `ns-list` op.  These are
now filtered out.
This change improves all cider commands relying on a completing read of
some namespace e.g. `cider-browse-ns` and `cider-find-ns`

[Fix #196] Rewritten dependencies polluting ns-list

---

src/cider/nrepl/middleware/util/instrument.clj
test/clj/cider/nrepl/middleware/util/instrument_test.clj

We already didn't instrument inside maps, but we still wrapped breakpoints around them. This is bad sometimes.
The fix is this [one line change](https://github.com/clojure-emacs/cider-nrepl/compare/master...Malabarba:master#diff-156621f66b9a5c16a8d5eabf6bc46cd7L285). The rest of the diff is cleanup related to this map thing.

[Fix clojure-emacs/cider#1134] Don't breakpoint maps in arglists

---

src/cider/nrepl/middleware/debug.clj
src/cider/nrepl/middleware/util/instrument.clj
test/clj/cider/nrepl/middleware/debug_test.clj
test/clj/cider/nrepl/middleware/util/instrument_test.clj

- Debugger's eval and inject also accept code non-interactively. Instead of sending :eval on the message's "input" entry, send something like `{:response :eval, :code 123}`. This allows cider.el to integrate regular eval commands with the debugger.  
*In short*, commands like `C-x C-e` or `C-c M-:` will evaluate code in the lexical context while debug-mode is active.
- Since the order inside maps is unreliable, try to use map keys as a coordinate. Affects #211.  
- There are now commands for inspecting values in the lexical context. `:inspect` and `:locals`, in particular.  
- When a form has no :cider-coor metadata, but it is a list and its `first` *does* have that metadata, this is probably a proper code form built by a macro (like the threading macros). The debugger will now use the …

More debugger

---

src/cider/nrepl/middleware/util/instrument.clj
test/clj/cider/nrepl/middleware/util/instrument_test.clj

We don't want breakpoints around `catch` or `finally`.

Fix instrumenting try forms

---

src/cider/nrepl/middleware/debug.clj
test/clj/cider/nrepl/middleware/debug_test.clj

Goes with https://github.com/clojure-emacs/cider/pull/1206
This it so we don't rely on the session bindings map, which was unreliable. In addition it should allow the debugger to work on cases where `*msg*` is not bound.

Rewrite the debugger a bit to depend less on *msg*

---

src/cider/nrepl/middleware/refresh.clj

I'm still refining the elisp bits for this, but am posting the middleware changes for review. The options are passed in as namespace-qualified function names, which must have zero arity. `before` is invoked before refreshing, and refreshing does not proceed if it throws an exception. `after` is invoked after refreshing.
`refresh-tracker` is now an agent, and the logic for refreshing dispatched using `send-off` - this means that only one `refresh` request will be being processed at any given time, so you don't have to worry about your `before` and `after` functions running concurrently or being retried. This is also means they won't lock up an nREPL thread if they block for a long time.
`*out*` and `*err*` are both captured and streamed back to the client while invoking both `before` and …

Add `before` and `after` options to refresh middleware

---

README.md
src/cider/nrepl/middleware/refresh.clj

* Sometimes the refresh tracker can get in a state that makes reloading impossible - this can happen if a file has been deleted, or if a circular dependency error occured. The `clear` op does the same thing as `clojure.tools.namespace.repl/clear`, resetting the refresh tracker to its default value. The trade-off of doing this is that stale code from any deleted files may not be completely unloaded - I'll document all of this in the client README when I add support for the op there.
* The problem with using `clojure.tools.namespace.repl/remove-disabled` directly is that it looks up namespaced keywords in each namespace's metadata, and these namespaced keywords are rewritten by mranderson, so will not match those in user code. We workaround this by constructing the correct keywords at …

Refresh improvements - clear op and support for disabling reloading of namespaces

---

src/cider/nrepl/middleware/util/instrument.clj
test/clj/cider/nrepl/middleware/util/instrument_test.clj

This change allows deftest forms to be debugged, by instrumenting the
test function that is attached to the var as metadata.

Instrument deftest for debugging

---

project.clj
src/cider/nrepl.clj
src/cider/nrepl/middleware/track_state.clj
test/clj/cider/nrepl/middleware/pprint_test.clj
test/clj/cider/nrepl/middleware/track_state_test.clj

This middleware keeps the client notified of what the current repl type is.
This makes it easier for cider.el to chose the right conneciton buffer, since we're now aware of which rpel buffers are cljs even if the user didn't create them with our own commands.

Add track-state middleware

---

src/cider/nrepl/middleware/debug.clj
src/cider/nrepl/middleware/track_state.clj
test/clj/cider/nrepl/middleware/track_state_test.clj

Goes with https://github.com/clojure-emacs/cider/pull/1301
The track-state middleware now keeps the client informed of loaded
namespaces as well. For each namespace, we transmit a map of:
- All interns (from symbol to the var's metadata). Only select metadata
keys are transmitted, currently that's:
- `:indent`
- `:cider-instrumented`
- `:macro`
- `:arglists`
- `:test`
- All refers not from clojure.core (from symbol to fully-qualified var name)
- All aliases (from symbol to namespace name)

Track namespace info as part of track-state

---

src/cider/nrepl/middleware/track_state.clj
test/clj/cider/nrepl/middleware/track_state_test.clj

- Don't build the namespace map ourselves, just use ns-map.
- Don't track changes in namespaces from jar files.
- Since the client still needs to know what's in these jar namespaces,
we send their info on the first message, but we ONLY do that for
namespaces that are :require'd by a source namespace. This guarantees
we only send namespaces that are potentially useful, and reduces the
amount of garbage we send on the first message
This fixes a lag of about 300ms between receiving eval result and
receiving the "done" status, which translated as a lag on printing the
repl prompt.
This might solve clojure-emacs/cider#1320, depending on the size of
project namespaces, but we should probably still offer a way to disable
it.

Rewrite the namespace part of track-state

---

src/cider/nrepl/middleware/track_state.clj
test/clj/cider/nrepl/middleware/track_state_test.clj

This should fix all lags associated with the new namespace tracking,
both the long delay at first connection and the ~1sec lag in the REPL.

[Fix clojure-emacs/cider#1320] Do state tracking in a future

---

README.md
project.clj
src/cider/nrepl.clj
src/cider/nrepl/middleware/out.clj
test/clj/cider/nrepl/middleware/out_test.clj

Automatically changes the root binding of *out* to print to any active
connections. An active connection is a session that has sent at least
one "eval" op and hasn't been closed.
We use an eval message, instead of the clone op, because there's no
guarantee that the message that sent the clone op will properly handle
output replies.
https://github.com/clojure-emacs/cider/issues/1328

New middleware: out.clj

---

src/cider/nrepl/middleware/util/java/parser.clj

Currently, the system property "apple.awt.UIElement" is unconditionally to "true" set right before the system property is used to decided whether or not the application will show an application icon in the osx dock. There is no way to override this behavior when using the repl. This commit only sets "apple.awt.UIElement" to "true" when the property is not already set via jvm flags or otherwise.
I'm working on a swing application where I would actually like the default behavior when apple.awt.UIElement is not set to true or is left unset. Basically, I like being able to command-tab between the GUI I'm working on and emacs where I'm making edits to the GUI.

don't override apple.awt.UIElement system property if explicitly set.

---

src/cider/nrepl/middleware/stacktrace.clj
test/clj/cider/nrepl/middleware/stacktrace_test.clj

This patch re-introduces the inner 'cause' of compiler exceptions.
These exceptions are not always informative, which may be why they were
hidden in 0a57231f1. For example when the compiler is complaining about
a syntax error, the exception often refers to a line number far from the
actual syntax problem.
However, the exceptions *can* be quite useful, for example when they
complain about an undeclared variable.
This patch re-introduces this additional detail. I'd be equally happy
with completely removing `extract-location`.  The output from the two
approaches is similar, and perhaps less code is better.

Extract more detail from compiler exceptions

---

src/cider/nrepl/middleware/out.clj
test/clj/cider/nrepl/middleware/out_test.clj

Connected sessions must send a message with an "out-subscribe" op in
order to have server messages forwarded to them. The forwarded outs are then
sent as replies to this message (so it must be able to handle out).

[Fix #266] Only forward server out to subscribed clients

---

src/cider/nrepl.clj
src/cider/nrepl/middleware/out.clj
src/cider/nrepl/print_method.clj
test/clj/cider/nrepl/print_method_test.clj

Instead of printing as
`  #object[clojure.core$_PLUS_ 0x4e648e99 "clojure.core$_PLUS_@4e648e99"]`
they are now printed as
`  #function clojure.core/+`

Abbreviate printing of some objects

---

src/cider/nrepl/middleware/info.clj
test/clj/cider/nrepl/middleware/info_test.clj

A followup to https://github.com/clojure-emacs/cider/pull/1374
Short summary: when project is using [Boot](https://github.com/boot-clj/boot), the source files are copied to temporary folder and class path points to that folder. This leads to ```cider-find-var``` opening a source file in temp folder instead of an original one.
The original class-path is stored by [Boot](https://github.com/boot-clj/boot) in a system property named ```fake.class.path``` (see https://github.com/boot-clj/boot/issues/249).
This fix checks if system property ```fake.class.path``` exists and if yes, assumes that ```Boot``` is used and resolves resources through a class-loader that knows about original paths.
I've tested it for my project and it works. I don't know how to cover this with unit tests, though. Any …

Correctly resolve resource full path in Boot projects

---

project.clj
src/cider/nrepl/middleware/debug.clj
src/cider/nrepl/middleware/pprint.clj
src/cider/nrepl/middleware/refresh.clj
src/cider/nrepl/middleware/stacktrace.clj
src/cider/nrepl/middleware/test.clj
test/clj/cider/nrepl/middleware/pprint_test.clj
test/clj/cider/nrepl/middleware/stacktrace_test.clj
test/cljs/cider/nrepl/middleware/cljs_pprint_test.clj

Context: clojure-emacs/cider#1179
This PR adds a new `wrap-pprint-fn` middleware, that accepts the set of all printing-related options that we currently use for the eval/stacktrace/test/refresh middlewares, in addition to a new `pprint-fn` option (which must be the name of the function to be used for printing, e.g. `"clojure.pprint/pprint"`). It then constructs a closure that wraps up all the options and the provided printing function, placing it into the request map (again under the `pprint-fn` key) so that subsequent middlewares can just call the function without having to care about all the different options.
Eventually I'd like to provide some alternative printers to `clojure.pprint/pprint` out-of-the-box, but ATM the main candidates ([fipp](https://github.com/brandonbloom/fipp); …

Custom pretty printing

---

project.clj
src/cider_nrepl/plugin.clj

Fixes #277.
The REPL will still start, and the client will warn about all the missing ops when it connects. Client-side, we should probably also check the Clojure version (using the `describe` op response), and perhaps sniff the `nrepl-server` buffer for the Leiningen warning. Then we can show a more meaningful warning in the REPL, since I don't think people tend to look at `nrepl-server` that often. That obviously only applies to `cider-jack-in` users - hopefully those connecting to a REPL running at the terminal will see it there :-).

Don't inject the middleware if its version requirements aren't met

---

src/cider/nrepl/middleware/stacktrace.clj
src/cider/nrepl/middleware/test.clj

This brings in commit a62f937 to be compatible with a bug fix going into cider 0.10.1.

Return cider-test result keys more specifically

---

src/cider/nrepl/print_method.clj
test/clj/cider/nrepl/print_method_test.clj

Tests pass.  I've pasted my comment from the issue thread below for reference.
Current print-method for an Atom is here:
https://github.com/clojure/clojure/blob/bc186508ab98514780efbbddb002bf6fd2938aee/src/clj/clojure/core_print.clj#L387-L408
Which looks like:
```
=> (println (atom {:foo :bar}))
#object[clojure.lang.Atom 0x54274a2b {:status :ready, :val {:foo :bar}}]
```
It looks like ':status' will always be ':ready' for an atom since atoms do not implement the "IPending" interface.  I propose we drop this information in the new print method since it's not useful.  New print output looks like the following:
```
=>(println (atom "{:foo :bar}"))
#atom[{:foo :bar} 0x54274a2b]
```
The identity hash code is moved to the end to keep it consistent with the print output for multifn.

Add print method and tests for atoms

---

src/cider/nrepl/print_method.clj
test/clj/cider/nrepl/print_method_test.clj

Previously, atoms containing strings would print incorrectly.  This way atom with strings will print correctly with both 'pr' and 'print'

Use 'pr-str' for getting a derefed atom string.

---

src/cider/nrepl/middleware/debug.clj
test/clj/cider/nrepl/middleware/debug_test.clj

This PR has a cider.el counterpart here: https://github.com/clojure-emacs/cider/pull/1517

Implement the :here debug action

---

src/cider/nrepl/middleware/debug.clj
src/cider/nrepl/middleware/util/instrument.clj
src/cider/nrepl/middleware/util/meta.clj
test/clj/cider/nrepl/middleware/debug_test.clj
test/clj/cider/nrepl/middleware/util/instrument_test.clj

This command skips all further breakpoints (like :continue), but prints
their values via println.

Implement a Trace command in the debugger

---

src/cider/nrepl/print_method.clj
test/clj/cider/nrepl/print_method_test.clj

More specifically, clojure.lang.IDeref. This would include atoms too,
but we already have a specialized print_method for them.

Implement a print-method for agents, futures, delays, promises, etc

---

project.clj
src/cider/nrepl.clj
src/cider/nrepl/middleware/debug.clj
src/cider/nrepl/middleware/enlighten.clj
src/data_readers.clj

This adds a middleware that instruments code in “eval” ops that provide an “enlighten” key. When the code is evaluated, information is sent through the debug channel regarding value of local variables and return value of functions.
In addition to the “enlighten” key (which is made available by Emacs as a minor mode), this feature can also be accessed by adding `#light` before a top-level sexp.

New feature: Enlighten

---

src/cider/nrepl/middleware/classpath.clj
test/clj/cider/nrepl/middleware/classpath_test.clj

Wraps  transport with a try/catch block and returns an error
message if there's a problem with getting the classpath. Added
tests for this as well.

Add error handling for classpath op

---

src/cider/nrepl/middleware/format.clj
test/clj/cider/nrepl/middleware/format_test.clj

Wrap format-code-reply's send in try/catch.
Deleted unused right-margin option.
Added tests to get to 100% coverage.

Add format-code exception & delete right-margin op

---

src/cider/nrepl/middleware/debug.clj
src/cider/nrepl/middleware/util/instrument.clj
test/clj/cider/nrepl/middleware/debug_integration_test.clj

Not entirely ready, but I would like to get some more eyes on this and see whether others agree with the approach.
The feature is conditional breakpoints - that is, breakpoints that will only enter the debugger when an expression is truthy.
Conditions are attached to forms as `:break/when` metadata. Example:
```clojure
(for [i (range 3)]
#dbg ^{:break/when (odd? i)
(inc i))
```
Evaluating this, you will stop in the debugger only once, when `i` is 1.
However, the primary use case (at least for me) is likely to be instrumenting a function with a conditional breakpoint. I have implemented this in cider as `C-u C-u C-M-x`, which prompts for an expression. This can be an expression of the function arguments. The form is then sent to cider-nrepl with `#dbg ^{:break/when (the expression)}` …

Conditional breakpoints

---

src/cider/nrepl/middleware/info.clj
test/clj/cider/nrepl/middleware/info_test.clj

- [x ] The commits are consistent with our [contribution guidelines](CONTRIBUTING.md)
- [x ] You've added tests to cover your change(s)
- [x ] All tests are passing
- [x ] The new code is not generating reflection warnings
- [n/a ] You've updated the readme (if adding/changing middleware)
Thanks!
Added coverage tests for the info middleware to get 100% coverage. There
are some TODO's listed in the test code since I wasn't clear on the
precise intent of certain methods.
There was a small correction made to the format-response function (the
stringified namespace wasn't merged into the response map where it
should have been, but no bug resulted since the stringified namespace
was added in subsequent steps anyway).
Slightly …

Add tests for info middleware and small correction

---

src/cider/nrepl/middleware/out.clj

Generalize out.clj code to support err

---

src/cider/nrepl/middleware/util/inspect.clj
test/clj/cider/nrepl/middleware/util/inspect_test.clj

This should hopefully fix clojure-emacs/cider#1602.
An infinite syntax is not a `list?`. Neither are Cons cells, and some other things. `sequential?` predicate covers all of them.

[c.n.m.u.inspect] Treat infinite sequences as lists

---

src/cider_nrepl/plugin.clj

This patch allows the cider-nrepl middleware to be injected into a project which does not depend on `org.clojure/clojure`, if and only if the user has explicitly provided `:exclusions [... org.clojure/clojure]`
in the `project.clj` file. This allows users who know what they're doing to take on the responsibility of providing an appropriate build of Clojure and thus use CIDER with forks albeit with a warning.
Replaces https://github.com/clojure-emacs/cider/pull/1603

Include cider-nrepl anyway when clj is excluded

---

src/cider/nrepl/middleware/util/java.clj
test/clj/cider/nrepl/middleware/info_test.clj
test/clj/cider/nrepl/middleware/util/java_test.clj

Thanks!
An issue where the URLs for Javadoc in Java 1.8 has a different format
than prior Java version, namely, parenthesis surrounding argument lists
have been changed to dashes. Added tests as well.

Fix Javadoc URLs for Java 1.8

---

src/cider/nrepl/middleware/debug.clj
test/clj/cider/nrepl/middleware/debug_integration_test.clj
test/clj/cider/nrepl/middleware/debug_test.clj

Previously, the var `*skip-breaks*` was storing a mode (:deeper,
:before, etc.) and a sequence of coordinates. However, it did not store
any information indicating what code the coordinates referred to.
This would lead to strange behavior when an :out or :here operation
would skip over code that called another instrumented function. The
debugger would treat the coordinates in *skip-breaks* as if they
referred to the code of the called function, and would seem (to the
user) to skip randomly over some or all of the function.
The fix:
1) Store *skip-breaks* as a map containing :mode, :coor, and :code,
where :code is the string of code that the :out or :here operation was
performed on.
2) Add logic to `skip-breaks?` to only skip if the to-be-skipped code
and the currently-being-debugged code …

Debugger: make skip-breaks depend on current code

---

src/cider/nrepl/middleware/inspect.clj
src/cider/nrepl/middleware/util/inspect.clj
test/clj/cider/nrepl/middleware/inspect_test.clj
test/clj/cider/nrepl/middleware/util/inspect_test.clj

- [n/a] You've updated the readme (if adding/changing middleware)
Thanks!
A couple of small bugs/inconsistencies in the inspector middleware.
1 - Setting the page size on the fly while using the inspector was not
working. Emacs was sending an integer to Cider, which was expecting a
string, causing a type conversion error (the tests were sending a
string, which is why it wasn't caught before). Also, the user can pass
in negative integers or a zero which would break the system, so added a
sanity check.
2 - Similarly, the push op expects a stringified integer in the :idx
slot. The elisp code was converting the supplied integer to a string
prior to sending it over the wire, so there was no error in the code,
but the …

Fix small inspector errors and improve tests

---

src/cider/nrepl/middleware/pprint.clj
test/clj/cider/nrepl/middleware/format_test.clj
test/clj/cider/nrepl/middleware/pprint_test.clj

Thanks!
The prior code had a difficult to test code block in `resolve-pprint-fn`
as well as a small piece of round about code in `wrap-pprint` , so these
functions were streamlined to help with testing/understanding. Behavior
is slightly changed since the resolve-pprint-fn will now throw different
exceptions based on the root cause of the exception (no such namespace
in classpath, no such var in an existing namespace, etc. This required a
slight change in the format-middleware tests). Otherwise, the
functionality of the code should be the same.
Added coverage tests to get to 100%. Error handling is actually done
elsewhere in the middleware stack (within the `eval` op).

Improve pprint middleware tests & simplify code

---

src/cider/nrepl/middleware/debug.clj
test/clj/cider/nrepl/middleware/debug_integration_test.clj
test/clj/cider/nrepl/middleware/debug_test.clj

NOTE: Depends on https://github.com/clojure-emacs/cider-nrepl/pull/311
Add optional force parameter to :out and :here ops.
When an `:out` or `:here` operation jumps past calls to other
instrumented functions, the debugger will normally stop in those
functions.
Passing a truthy `force` parameter to one of these ops will cause the
debugger to skip all breaks outside of the currently debugged form,
effectively forcing it to immediately step to the location specified in the 
`:out` or `:here` operation.

Force step out

---

src/cider/nrepl/middleware/util/namespace.clj
test/clj/cider/nrepl/middleware/util/namespace_test.clj

Thanks!
Since windows uses backslashes this results in an invalid regular
expression throwing a PatternSyntaxException. By passing the
project-root through Pattern/quote it is escaped properly for use in
a regular expression

quote project dir when used in regex

---

src/cider/nrepl/middleware/util/meta.clj
test/clj/cider/nrepl/middleware/util/instrument_test.clj

Instrumentation would throw when trying to macroexpand code containing a
namespace object with metadata.
The logging macros in clojure.tools.logging embed the current namespace
object into the code at macroexpansion time. Instrumenting a function
that contained logging calls would throw an exception if the current
namespace had metadata (eg: a docstring).
This is because Namespace has the unusual property of implementing
IMeta (so you can call `(meta *ns*)`), but not IObj (so `(with-meta *ns*
...)` throws).

Fix exception when instrumenting code with embedded namespace

---

src/cider/nrepl/middleware/apropos.clj
src/cider/nrepl/middleware/classpath.clj
src/cider/nrepl/middleware/complete.clj
src/cider/nrepl/middleware/format.clj
src/cider/nrepl/middleware/info.clj
src/cider/nrepl/middleware/inspect.clj
src/cider/nrepl/middleware/macroexpand.clj
src/cider/nrepl/middleware/ns.clj
src/cider/nrepl/middleware/out.clj
src/cider/nrepl/middleware/resource.clj
src/cider/nrepl/middleware/stacktrace.clj
src/cider/nrepl/middleware/trace.clj
src/cider/nrepl/middleware/undef.clj
src/cider/nrepl/middleware/util/error_handling.clj
test/clj/cider/nrepl/middleware/apropos_test.clj
test/clj/cider/nrepl/middleware/classpath_test.clj
test/clj/cider/nrepl/middleware/complete_test.clj
test/clj/cider/nrepl/middleware/format_test.clj
test/clj/cider/nrepl/middleware/info_test.clj
test/clj/cider/nrepl/middleware/inspect_test.clj
test/clj/cider/nrepl/middleware/macroexpand_test.clj
test/clj/cider/nrepl/middleware/ns_test.clj
test/clj/cider/nrepl/middleware/resource_test.clj
test/clj/cider/nrepl/middleware/trace_test.clj
test/clj/cider/nrepl/middleware/undef_test.clj
test/clj/cider/nrepl/middleware/util/error_handling_test.clj

- [x ] The commits are consistent with our [contribution guidelines](CONTRIBUTING.md)
- [ x] You've added tests to cover your change(s)
- [ x] All tests are passing
- [ x] The new code is not generating reflection warnings
Thanks!
A new util ns in `cider.nrepl.middleware.util.error-handling` which
provides the `with-safe-transport` macro, abstracting away transport,
error handling, and stacktrace analysis. Most middlewares were updated
to use this system, and the tests were updated to reflect these changes.
In order to utilize the nicely formatted stacktraces stuffed into these
responses, concurrent changes have been made to CIDER and will be
submitted as a PR as well.

Abstract away op error handling

---

README.md
project.clj
src/cider/nrepl.clj
src/cider/nrepl/middleware/version.clj
test/clj/cider/nrepl/middleware/version_test.clj

Thanks!
This middleware is mostly here to address bug #202
https://github.com/clojure-emacs/cider-nrepl/issues/202. The descriptor
has a :describe-fn key, providing a function which will return a
map. This map will be merged into the :aux map returned by nRPEL's
built-in "describe" op. A regular op version of this same functionality
is provided via the "cider-version" op.

Supply CIDER version info via nREPL "describe" op

---

src/cider/nrepl/middleware/debug.clj
test/clj/cider/nrepl/middleware/debug_integration_test.clj

This commit implements "step in" for the debugger.
When stepping past a form that is a call to a function stored in a var,
prompt the user with the option to step in to the called function.
The prompt takes the form "Step in to foo/bar?", where "foo/bar" is the
function as it appears in the source, and the options are "yes" and "no.
Selecting "no" will display the result of the function, just as it
always has. Note that because the key for "no" is the same as the key
for "next", those in the habit of rapidly hitting "n" will notice little
difference to their workflow, although more presses of "n" will be
required - one extra for each function call.
Selecting "yes" will instrument the called function and then step in to
it. The instrumentation is done in a special way. It is not simply …

Debugger: Step in

---

src/cider/nrepl/middleware/debug.clj
test/clj/cider/nrepl/middleware/debug_integration_test.clj
test/clj/cider/nrepl/middleware/debug_test.clj
test/clj/cider/nrepl/middleware/util/instrument_test.clj

3 Fixes:
- The cond->> form in debug.clj was just wrong
- Removed tests that assumed a specific ordering of debugger commands
- Fixed instrument test for reify, which changed due to no longer
wrapping the second symbol in `.` forms in a breakpoint

Fix failing tests

---

src/cider/nrepl/middleware/debug.clj
test/clj/cider/nrepl/middleware/debug_integration_test.clj

The new step-in command makes it easy to step in (often accidentally) to
a function in clojure.core. But instrumenting clojure core functions is
dangerous, and can result in a stack overflow that crashes the nrepl
process. In fact, just instrumenting `clojure.core/symbol?` (without
even debugging it) causes a stack overflow. I'm not entirely sure yet
how this happens, but it seems safest to just prevent stepping in to all
core functions.

Don't step in to clojure.core functions

---

src/cider/nrepl/middleware/apropos.clj
src/cider/nrepl/middleware/ns.clj
src/cider/nrepl/middleware/util/namespace.clj
test/clj/cider/nrepl/middleware/apropos_test.clj
test/clj/cider/nrepl/middleware/ns_test.clj
test/clj/cider/nrepl/middleware/track_state_test.clj
test/clj/cider/nrepl/middleware/util/namespace_test.clj

For clojure-emacs/cider#1564. I still have to write the tests, update documentation etc. But is the basic idea correct ?
And on emacs, we can have a custom var like,
```
(defcustom cider-filter-prefixes '("cider.nrepl" "refactor-nrepl")
"Cider middleware would filter out information from namespaces starting with `cider-filter-prefixes'"
:type 'list
:group 'cider
:package-version '(cider . "0.13.0"))
```
which will be nil, if we want all the internals visible. Also, if we jack-in from `cider-nrepl` project, we don't have to set it to nil. It picks up the un-inlined versions of deps. But its good to keep it configurable.
Some screenshots;
ns-browser
apropos
If the user types out the entire ns form the ns-browser, he'll still get the vars listed. But thats ok I guess.

Cider's namespaces and vars filtered from ns-list and apropos

---

src/cider/nrepl/middleware/util/namespace.clj

Fix c.n.m.u.namespace/project-namespaces broken for Boot projects

---

src/cider/nrepl/middleware/util/meta.clj
test/clj/cider/nrepl/middleware/ns_test.clj
test/clj/cider/nrepl/middleware/track_state_test.clj
test/clj/cider/nrepl/middleware/util/meta_test.clj
test/cljs/cider/nrepl/middleware/cljs_ns_test.clj

Include docstring in ns-vars-with-meta to be able to show first line of docstring in cider namespace browser (https://github.com/clojure-emacs/cider/issues/1577).

Include docstring in ns-vars-with-meta

---

project.clj
src/cider/nrepl/middleware/complete.clj
src/cider/nrepl/middleware/resource.clj
test/clj/cider/nrepl/middleware/resource_test.clj

~~I still couldn't get the auto-complete to work for the form, `(resource "|")`. But that is an additional feature and does not block this upgrade. Everything else works.
I'm working on it and we can add that later. It wouldn't require any changes to the middleware.~~
Thanks!
/cc @alexander-yakushev

Bump compliment to 0.3.0-SNAPSHOT

---

src/cider/nrepl/middleware/test.clj

We now capture test input as generated by `test.check` and pass it on to
cider_test.el for display.

[Fix clojure-emacs/cider#1825] Capture test input

---

.travis.yml
project.clj
src/cider/nrepl/middleware/info.clj
src/cider/nrepl/middleware/util/spec.clj
test/clj/cider/nrepl/middleware/info_test.clj
test/spec/cider/nrepl/middleware/info_test.clj

Thanks!
This is not ready for a merge. I'm not really sure how do we make the nREPL use Clojure 1.9, and still maintain backwards compatibility with older versions. While developing this, I just bumped the version for the `:provided` profile, but I'm sure that's not the right way to do it. Please help me figure out the correct `project.clj` for this feature.

Display Clojure.spec in the doc buffer

---

README.md
src/cider/nrepl/middleware/macroexpand.clj
test/clj/cider/nrepl/middleware/macroexpand_test.clj

`macroexpand-step` expands a form one macro subform at a time, creating
a [macrostep](https://github.com/joddie/macrostep)-like effect.
This a step (hehe) towards addressing clojure-emacs/cider#1850.

Add `macroexpand-step`

---

README.md
src/cider/nrepl/middleware/inspect.clj
src/cider/nrepl/middleware/util/inspect.clj
test/clj/cider/nrepl/middleware/inspect_test.clj
test/clj/cider/nrepl/middleware/util/inspect_test.clj

In the inspector a path is a series of functions to be applied to the inspected data structure to arrive at the current destination. The idea is to render the path in the inspector buffer, and to give ability to copy the path to kill-ring by pressing `w`.
Path is represented as if the inspected value was threaded with `->`.
For example, in a structure:
```clojure
{:a [{:b 1} {:c 2}] :d 42}
```
after navigating to `2` the path shall be `:a (nth 1) :c`. Navigating to `:b` yields `:a (nth 0) (find :b) first`.
Haven't modified the README yet, waiting for the green light for the feature in general.

Add path tracking functionality to inspector

---

src/cider/nrepl/middleware/out.clj

This builds on @Malabarba's work in #304 in order to fix https://github.com/clojure-emacs/cider/issues/1588 and https://github.com/clojure-emacs/cider/issues/1896.  In addition, this also redirects Java's `System/out` and `System/err` to `*out*` and `*err*` (they're confusingly not the same) so that everything you'd expect gets printed at the repl.
I didn't add tests because I'm not sure how to go about doing that without actually spinning up an nrepl server.  I'm glad to accept guidance on this, though.  Existing tests do pass.

Output to each session's *err* in the same manner as *out*

---

src/cider/nrepl/middleware/track_state.clj
test/clj/cider/nrepl/middleware/track_state_test.clj

Ensure that ns cache has clojure(script) core

---

src/cider/nrepl/middleware/info.clj
test/spec/cider/nrepl/middleware/info_test.clj

Fixes https://github.com/clojure-emacs/cider/issues/1914 
Every spec is on a newline, right from the first `(cat :start int? :end int?)` because this way, all them are aligned irrespective of the length of the combinator, `and` in this case.
Thanks!

[Fix #1914] Proper formatting of spec descriptions

---

project.clj
src/cider/nrepl/version.clj
src/cider/tasks.clj

This adds the task for https://github.com/clojure-emacs/cider/pull/1751
In order to try the command:
```
boot -v -d org.clojure/tools.nrepl:0.2.12 -d cider/cider-nrepl:0.15.0-SNAPSHOT -i "(require 'cider.tasks)" cider.tasks/add-middleware -m cider.nrepl/cider-middleware
```
And check the final few lines of the debug log:
```
Boot's default middleware: []
After cider's injection: [cider.nrepl/cider-middleware]
```

Add cider.tasks/add-middleware boot task

---

project.clj
src/cider/nrepl/middleware/complete.clj
test/clj/cider/nrepl/middleware/complete_test.clj

Related to alexander-yakushev/compliment#45. While the issue is mostly solved automatically, explicit flushing might sometimes still be necessary.
Sister PR is at clojure-emacs/cider#1943.

Add complete-flush-caches command to force clear Compliment's caches

---

src/cider/nrepl/middleware/out.clj

Original `*out*` and `*err*` are still bound to the original
System/out and System/err, which causes output sent to them to end
up in the server buffer. This was undesired.
As requested here: https://github.com/clojure-emacs/cider/pull/1907#issuecomment-270955541

Avoid printing to original `*out*` and `*err*`

---

src/cider/nrepl/middleware/util/namespace.clj

This PR adds error handling to the `ns-path` function for catching exceptions propagated from `tools.reader` (breaking change going from 0.2.11 to 0.3.0-alpha1).

[Fix #399] Catch ns-path exceptions propagated from tools.reader

---

project.clj
src/cider/nrepl/middleware/stacktrace.clj
test/cljs/cider/nrepl/middleware/cljs_stacktrace_test.clj

As of https://github.com/cemerick/piggieback/pull/72 piggieback supports *e so this change enables the stacktrace middlware for piggieback.
The change is backwards compatible with older versions of piggieback which don't set *e. A :status :no-error response is sent as before.

Enable stacktrace support for piggieback.

---

src/cider/nrepl/middleware/apropos.clj
src/cider/nrepl/middleware/info.clj
test/clj/cider/nrepl/middleware/apropos_test.clj
test/clj/cider/nrepl/middleware/info_test.clj

Fixes #409.
Some special forms (e.g. `if`) are included in apropos if the `search-ns` is nil or
`clojure.core`.
Included special forms are those those with documentation in `clojure.repl`,
as well as `&`, `catch`, and `finally`, the first of which uses the
documentation of `fn` and the others that of `try`.
**Update**:
With Lein 2.7.1, this passes:
```
$ lein with-profile +master,+test-clj test
Ran 181 tests containing 1118 assertions.
0 failures, 0 errors.
```
Whereas this does not:
```
$ lein with-profile +master,+plugin.mranderson/config,+test-clj test
Exception in thread "main" java.io.FileNotFoundException: Could not locate fipp/edn__init.class or fipp/edn.clj on classpath., compiling:(cider/nrepl/middleware/pprint.clj:1:1)
at clojure.lang.Compiler.load(Compiler.java:7391)
...
``` …

Include special forms in apropos

---

src/cider/nrepl/middleware/info.clj
test/clj/cider/nrepl/middleware/info_test.clj

Fixes #411.
forms-str now looks like:
"(.instanceMember instance args*)\n(.instanceMember Classname args*)"
arglists-str now looks like:
"[x]\n[x y]\n[x y z]"
Changes include:
- No extraneous whitespace
- Newlines
Previously, the two had inconsistent formats.
arglists-str looked like:
"([x] [x y] [x y z])"
forms-str looked like:
"  [(.instanceMember instance args*)  (.instanceMember Classname args*)]"
Thanks!

Change format of forms-str and arglists-str

---

src/cider/nrepl/middleware/format.clj

This delays loading of cljfmt until it's used. It drops about 1 second of initial load time for me.
Reference: clojure-emacs/cider#1717

delay cljfmt.core require to decrease initial load time

---

.travis.yml

to fix hack to use newer version of lein when only lein1 was available
on travis. no confusing exception anymore during environment setup.
trigged by a conversation on #417

Use lein2 on travis

---

src/cider/nrepl/middleware/info.clj

This fixes a case where in clojurescript the `:file` is stored as an
absolute path, meaning it points to a temporary file in boot.
It uses java.nio.file.Path to find all paths with the prefixes deleted,
and filters them until it finds one on the classpath. This implicitly
finds the longest one.
If it cannot find a contracted version of the file on the classpath, it
will pass through the original absolute path which points to a temporary
file.
A small optimisation here is doing this only for boot. But that does
mean that the results will be different for boot & lein as opposed to
previously where it was clj & cljs. I've not tested if there's a
performance improvement, but it will likely reduce unexpected behaviour.
| | CLJ | CLJS |
|-|-----|----------
| Boot | `:resource` |`:resource` most …

Find relative path for cljs & boot in info [#421]

---

project.clj

Both boot/base and boot/core seem necessary. For reasons I'm uncertain
of, neither depends on the other through their pom.xml. This could be a
mistake, or it could be due to how boot must isolate it's pods.

Fix [#418] Add boot as a dev dependency

---

src/cider/nrepl/middleware/complete.clj
src/cider/nrepl/middleware/debug.clj
src/cider/nrepl/middleware/info.clj
src/cider/nrepl/middleware/macroexpand.clj
src/cider/nrepl/middleware/ns.clj
src/cider/nrepl/middleware/track_state.clj

`grab-cljs-env` peeks into the message for the resolved `:session` key,
this will only have happened if the tns session middleware has been run
over the message.
TNS is consistent in how it orders middleware, so I wasn't able to
trigger this bug, but #345 seems like it could be caused by this.

Require tns/session where grab-cljs-env is used

---

README.md

Fix namespace of `wrap-spec` in README

---

src/cider/nrepl/middleware/debug.clj
src/cider/nrepl/middleware/enlighten.clj
test/clj/cider/nrepl/middleware/debug_test.clj

Fixing #420,  clojure-emacs/cider#2039 and clojure-emacs/cider#2004

Fixing the debugger "wrong namespace" issues. 

---

src/cider/nrepl/middleware/pprint.clj

load-file can produce an eval message. Non-deterministically load-file
was before/after pprint middleware. This would mean that pprint would
sometimes work for load-file, and not other times, dependent upon a JVM
restart.
This makes https://github.com/tpope/vim-fireplace/pull/301 work
As an aside: I can't get the tests to pass locally even on master, so I'm depending on the CI

Ensure pprint is after load-file

---

src/cider/nrepl/middleware/pprint.clj

None of the functionality currently relying on `wrap-pprint-fn` is pretty printing. The reason is that `*print-right-margin*` is always set to nil as `@session` is not binding it.
To reproduce 
```clj
(throw (ex-info "blabla" {:some.ns/bablabla.bla "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
:other.ns/bablabla.bla "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"}))
```
and you should see ex-info data printed in one long line within the stack trace.

Fix *print-right-margin* binding in `wrap-pprint-fn`

---

src/cider/nrepl/middleware/test.clj

When I required the current master branch of this repo I ran into: `Invalid token: ::clojure.test/once-fixtures`. The double colon keyword prefix only works with namespace aliases that are set up in the current namespace. In this case there is not a namespace alias "clojure.test", so these keywords are invalid.

Fix invalid namespaced keywords

---

src/cider/nrepl/middleware/debug.clj

Any forms that contain reader conditionals cannot be instrumented: 
```clj
(defn tt [a]
(let [b (+ a 1)]
#?(:clj (println "clj")
:cljs (println "cljs"))))
```
The reason is that conditionals are disabled by default in clojure's readers.

Fix broken instrumentation of forms with #? conditionals

---

project.clj
src/cider/nrepl.clj
src/cider/nrepl/middleware/apropos.clj
src/cider/nrepl/middleware/classpath.clj
src/cider/nrepl/middleware/complete.clj
src/cider/nrepl/middleware/debug.clj
src/cider/nrepl/middleware/enlighten.clj
src/cider/nrepl/middleware/format.clj
src/cider/nrepl/middleware/info.clj
src/cider/nrepl/middleware/inspect.clj
src/cider/nrepl/middleware/macroexpand.clj
src/cider/nrepl/middleware/ns.clj
src/cider/nrepl/middleware/out.clj
src/cider/nrepl/middleware/refresh.clj
src/cider/nrepl/middleware/resource.clj
src/cider/nrepl/middleware/spec.clj
src/cider/nrepl/middleware/stacktrace.clj
src/cider/nrepl/middleware/test.clj
src/cider/nrepl/middleware/trace.clj
src/cider/nrepl/middleware/track_state.clj
src/cider/nrepl/middleware/undef.clj
src/cider/nrepl/middleware/util/error_handling.clj
src/cider/nrepl/middleware/version.clj
test/clj/cider/nrepl/middleware/apropos_test.clj
test/clj/cider/nrepl/middleware/debug_integration_test.clj

Addresses #218  and clojure-emacs/cider#1717. 
It now takes only 0.25s for me to load `cider.nrepl.clj`. So startup time is now compatible with `lein repl` with an empty project.  Some extra work could be done on emacs side to avoid loading extra things (like debugger) on startup. 
I will pile a couple more related commits here in the following days to further fix loading of the debugg.clj, error_handling.clj and maybe something else.

Dynamically load middleware

---

src/cider/nrepl/middleware/track_state.clj
src/cider/nrepl/middleware/util/meta.clj
test/clj/cider/nrepl/middleware/track_state_test.clj

This fixes the problem that functions defined with `def`, e.g. `(def f (fn [] ...))` gets font locked as non-function vars, because they have no `:arglists` in their metadata. Needs https://github.com/clojure-emacs/cider/pull/2086
(I have not updated Cider's CHANGELOG.md, because I didn't know what to call the next version.)

Fix fns defined with def not font locked as fns

---

src/cider/nrepl/middleware/util/inspect.clj

This type hint causes a crash on arrays of primitive types, like [I and [C,
because neither are subclasses of java.lang.Object. Resolves
https://github.com/clojure-emacs/cider/issues/2077.
I'm getting a crash when running the repl or test suite, both on master and with this change.

Fix crash when inspecting primitive arrays

---

src/cider/nrepl/middleware/stacktrace.clj
test/spec/cider/nrepl/middleware/stacktrace_spec_test.clj

Accompanies clojure-emacs/cider#2082.

Implement dedicated clojure.spec/assert stacktrace handling

---

project.clj
src/cider/nrepl.clj
src/cider/nrepl/middleware/pprint.clj
src/cider/nrepl/middleware/version.clj
src/cider/nrepl/version.clj
test/clj/cider/nrepl/middleware/version_test.clj

These are extra fixes related to #438.  
- Better names.
- Better docs.
- Move pprint and version wrappers along all others for consistency.
- Inhibit concurrent loading of deferred middleware. Should fix clojure-emacs/cider#2092.

Deferred middleware extra fixes

---

src/cider/nrepl/middleware/out.clj

The proxy for `OutputStream/write` was only handling the case that its single argument was a byte array, but the super class also allows for a single character (int) to be passed to `write`.
This was causing a problem for me when I turned on debugging output for SSL connections (using `-Djavax.net.debug=all`).

Handle additional overloaded version of write.

---

src/cider/nrepl/middleware/info.clj
src/cider/nrepl/middleware/util/java.clj
test/clj/cider/nrepl/middleware/info_test.clj

Adds available jdk sources to the ClassLoader used to resolve boot project
resources by the 'info' op. This way, e.g. (cider-var-info  "java.lang.String"),
can return a "file" entry with an absolute url to the source, instead of just
the relative resource path.
Thanks!

Fix jdk source code lookup for boot projects

---

src/cider/nrepl/middleware/classpath.clj
src/cider/nrepl/middleware/util/misc.clj
test/clj/cider/nrepl/middleware/classpath_test.clj
test/clj/cider/nrepl/middleware/util/misc_test.clj

Boot manages the classpath dynamically through filesets, so
`java.class.path` does not include the source paths. Boot provides
access to the original directories via the `fake.class.path` system
property. Use this `fake.class.path` property instead of
`java.class.path` for Boot projects.

Use fake.class.path as classpath in Boot projects

---

src/cider/nrepl/middleware/stacktrace.clj
test/clj/cider/nrepl/middleware/stacktrace_test.clj

This makes it easier for tooling which has a native concept of error list to
integrate with the stacktrace op.
In this case, that tool is Vim.
Another change I made arbitrarily is to include cljc files as things upon which
ns & var are resolved for. I have tested this, and it works.
It would be get to some additional feedback on:
* Does this make things better for Emacs in terms of cljc?
* Is this an improvement that would be useful to emacs
* Does my additional step for invokeStatic's make sense? ( I wasn't getting files without it! )
I looked at adding line-shift to the server, but I found it to be grossly inaccurate in most cases. An explanation for it would be useful, as I suspect I was using it wrong given the massively incorrect offsets it caused for, e.g. `load$invoke`.
Before …

Find full path for stacktrace frames

---

src/cider/nrepl/middleware/util/misc.clj

--------
#461 's modify.
There is two versions of java 9.
(https://en.wikipedia.org/wiki/Java_version_history#Java_SE_9)
The one is "JAVA SE 9" released at 2017-09-21. this version returns just "9".
but "JAVA SE 9.0.1" released at 2017-10-17 returns "9.0.1".
The first example is for "JAVA SE 9" and second example is for "JAVA SE 9.0.1" :)
example 1> (case of JAVA SE 9)
pc:~$ java -version
java version "9"
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)
(System/getProperty "java.version")
> "9"
java-api-version
> nil
(we expect "9")
example 2> (case of JAVA SE 9.0.1)
pc:~$ java -version
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java …

for java9's version checking

---

src/cider/nrepl/middleware/util/meta.clj

Part of clojure-emacs/cider#2150
Let CIDER take care of as much formatting as possible.

Minimize string formatting in `format-spec`

---

src/cider/nrepl/middleware/spec.clj
src/cider/nrepl/middleware/util/meta.clj
test/clj/cider/nrepl/middleware/spec_test.clj
test/spec/cider/nrepl/middleware/info_test.clj

Make spec meta for info middleware take spec using spec middleware `spec-form` instead of `clojure.spec/describe`
**This needs to be merged together with Cider fix!**  https://github.com/clojure-emacs/cider/issues/2029

[Fix #425] Using spec middleware spec-form instead of clojure.spec.alpha/form for

---

.travis.yml
project.clj

The `:test-cljs` profile uses ClojureScript `1.7.189`, which uses `(require ...)` instead of `(:require ...)` in the ns form of `base64_vlq.clj`. This is fixed in clojure/clojurescript@48b83d9.
b63b153 tries to correct this by specifying a higher ClojureScript version in the `:1.9` profile, but this fails because the `:test-cljs` profile comes later.
We resolve this by matching each version of Clojure with a compatible version of Clojurescript in the version profiles.

Fix CLJS tests

---

src/cider/nrepl/middleware/util/java/parser.clj

For example, this should be enough info for goto-definition:
```clojure
((juxt :file :line)
(cider.nrepl.middleware.util.java.parser/source-info
'clojure.lang.RT))
```

source-info should return absolute path

---

.gitignore
.travis.yml
Makefile
project.clj
test/clj/cider/nrepl/middleware/debug_integration_test.clj

This PR introduces the following:
- adds a `Makefile` with targets to use in `travis.yml`, or can be used manually too
- excludes some problematic namespaces and tests from `cloverage` instrumentation, where instrumentation would cause tests to throw exceptions and/or fail.
- drops `cloverage --coveralls` completely, leaving only `cloverage --codecov`
- adds Oracle JDK 9 to the test matrix
---

[Fix #457] Reinstate cloverage testing by omitting problem namespaces

---

src/cider/nrepl/middleware/test.clj
src/cider/nrepl/middleware/test/extensions.clj

Fix #336
This basically brings [pjstadig/humane-test-output](https://github.com/pjstadig/humane-test-output)'s functionality into CIDER itself.

Add test extension to include expected / actual diffs

---

src/cider/nrepl/middleware/test/extensions.clj

Per @pjstadig's [comment](https://github.com/clojure-emacs/cider-nrepl/pull/478#pullrequestreview-90616379).

Add `assert-expr` for `clojure.core/=` for test extensions

---

test/clj/cider/nrepl/middleware/classpath_test.clj

`classpath-reply` takes a single arg, msg; is not a thunk
last failing test was an arity mismatch on classpath-repl

Fix classpath error handling redef arity

---

Makefile

Workaround for #489. It's important we get CI working properly until the [Orchard](https://github.com/clojure-emacs/orchard) port is complete.

Stop using `mranderson` for testing

---

.travis.yml
Makefile

These failures are unrelated to the nREPL itself.
1. CLJS doesn't build on JDK9 because it depends on a package deprecated in JDK9 (javax.xml.bind). CLJS-2377 tracks it. It has been fixed on master, but not yet released. After that, we can enable CLJS-1.9 tests on JDK9, but not the others.
2. CLJS-1.9 also doesn't build on JDK7 anymore ? I think this is because of a dependency on the closure-compiler which requires JDK8 or higher (https://github.com/google/closure-compiler/wiki/Releases#september-10-2017-v20170910)
/cc @gonewest818 
Thanks!

Disable failing tests

---

src/cider_nrepl/main.clj

This is useful in the context of clojure tools, and clojure.main, where
you can use `-e` to evaluate some code. I ended up with this for `clj`
command line:
```
clj -Sdeps '{:deps {refactor-nrepl {:mvn/version "2.3.1"} com.gfredericks.dominic/debug-repl {:mvn/version "0.0.1"} cider/cider-nrepl {:mvn/version "0.17.0-MYFORK"} }}' -e '(require (quote cider-nrepl.main)) (cider-nrepl.main/init ["com.gfredericks.debug-repl/wrap-debug-repl"])'
```
I was unable to test with CIDER due to master not building.

Add function for starting nrepl with middleware

---

.travis.yml
Makefile
project.clj

This seems likely to conflict with the changes @ckoparkar has in #494, so I'm submitting this mainly for visibility. An early look. I can take care of the reconciliation after #494 is merged.
The changes are analogous to what was done in clojure-emacs/orchard#10, follow the link for deeper explanation.
Left to do:
- debug the orchard build (as of now the deploy job isn't actually deploying)
- add encrypted environment variables where noted in `.travis.yml`
----
Thanks!

Fix #497 Auto-publish to clojars

---

.travis.yml
Makefile
project.clj
src/cider_nrepl/main.clj

* `lein-sysutils` offloads the parsing of the JDK version number to the commons-lang3 library. The benefit is that we don't have to invent tricky regex syntax and anticipate new versioning conventions such as JEP 223 (http://openjdk.java.net/jeps/223). `lein-sysutils` uses reflection to parse the available fields in org.apache.commons.lang3.SystemUtils, which means this mechanism should be fairly future-proof as long as the underlying library is actively maintained.
* Also fixes two CI issues by updating the conditional test in the deploy stage in `.travis.yml`
1. While `make release` creates a new version tag from which the
release should build and deploy, it turns out the resulting CI job
does not run the deploy task, because for those jobs the branch name
is not "master".  With this …

[Fix #500] simplify java version detection

---

src/cider/nrepl/middleware/refresh.clj
test/clj/cider/nrepl/middleware/refresh_test.clj

There are two things here: honor `set-refresh-dirs`, and honor `::load` metadata.
The directories to scan for a refresh can be configured with
`clojure.tools.namespace/set-refresh-dirs`. This makes CIDER honor this
configuration when set.
Specific namespaces can be excluded from being loaded or unloaded by setting
metadata on the namespace, for which there are convenience methods in
clojure.tools.namespace.repl. The docstrings of these methods say that setting
`:clojure.tools.namespace.repl/load false` should imply
`:clojure.tools.namespace.repl/unload false`. This makes CIDER honor that
convention.
Thanks!

Honor clojure.tools.namespace config and conventions

---

project.clj

just a simple dependency bump. have checked and works for me.
Steps to recreate:
```
(ns fizzbuzz.user)
(defn baz [] 1)
(ns fizzbuzz.core
(:require [fizzbuzz.user :as user]))
```
then at a repl `fizzbuzz.core> (user/)` would not see any auto complete.
This does not depend on the name of the namespace (`fizzbuzz.user`) but on the alias, `user`. If you rename to `usern` autocomplete works again.

[#508] Bump compliment so that namespaces aliased as user autocomplete

---

README.md

Per Bozhidar in https://github.com/clojure-emacs/cider-nrepl/issues/447#issuecomment-364812922 we are documenting the necessity of manual namespace resolution until #464 is resolved.
- [n/a] You've added tests to cover your change(s)
- [n/a ] All tests are passing
- [n/a] The new code is not generating reflection warnings
once a PR is merged, but **only** if the CI build is green.
*If you're just starting out to hack on cider-nrepl you might find
this [article](https://juxt.pro/blog/posts/nrepl.html) and the
Thanks!

Document embedded-nREPL workaround for #447 in README

---

src/cider/nrepl/middleware/test.clj

Partially address clojure-emacs/cider#2215.
Users should be able to define new message types.
With this change, such new messages will only be handled properly if `report` produces a map adhering to the schema of that of an existing type (e.g. `:fail`). This could be another point of extension in the future.

Use multimethod for `cider.nrepl.middleware.test/report`

---

CHANGELOG.md
src/cider/nrepl/middleware/util/cljs.clj

I noticed we're still carting around some legacy code for compatibility with piggieback 0.1 and I think it's time to remove it.

Remove support for piggieback 0.1.x

---

src/cider/nrepl/middleware/inspect.clj
test/clj/cider/nrepl/middleware/inspect_test.clj
test/cljs/cider/nrepl/middleware/cljs_inspect_test.clj

All of the useful work was done in clojure-emacs/orchard#24.
Not editing CHANGELOG here since nothing useful happened in cider-nrepl. I can, however, edit the CHANGELOG in cider if you like, since changes in Orchard are user-facing.

Fix print-length bug and fix integration tests

---

README.md
src/cider/nrepl/middleware/test/extensions.clj
test/clj/cider/nrepl/middleware/test/extensions_test.clj

`(is (= ...))` tests executed in cider currently fail if the first
argument to = is not pure as it is evaluated multiple times inside
`=-body`. By caching the value, this can be prevented.
This fixes clojure-emacs/cider/issues/2233
Example:
```
;; before
cider> (let [x (atom 0)]
(is (= (swap! x inc) 1))
@x)
;; => 2
;; after
cider> (let [x (atom 0)]
(is (= (swap! x inc) 1))
@x)
;; => 1
```
----

Fix test.extensions =-body: Only evaluate first argument once

---

src/cider/nrepl/middleware/test.clj
test/clj/cider/nrepl/middleware/test_selector_tests.clj
test/clj/cider/nrepl/middleware/test_test.clj

Test all and test ns understand `leiningen` style test selectors, eg
metadata markers on `deftest`s. No support for namespace level metada
markers for now.
If test selector is specified only the test(s) run that have that
selector in their metadata.

Add test selector support

---

src/cider/nrepl/middleware/util/cljs.clj

copied code wasn't updated. this fixes the cemerick piggieback check

Require cemerick piggieback with correct namespace

---

src/cider/nrepl.clj
src/cider/nrepl/middleware/content_type.clj
src/cider/nrepl/middleware/slurp.clj

Follows up from #517.
- Fixes a bug where the `"slurp"` op was not correctly registered with nREPL, leading to the server rejecting otherwise valid `"slurp"` requests.
- Fixes a bug where base64 encoding would produce a byte[] result which nREPL would make a mess of, rather than a string for simple transport.
- Fixes a bug where the `"slurp"` response would include its own `"done"` status, really messing up the REPL logic which expects a separate `"done"` result.

More images work.

---

src/cider/nrepl/middleware/test.clj
test/clj/cider/nrepl/middleware/test_test.clj

This is the original API before the API was deprecated.

Accept non-namespaced tests in backwards compat

---

README.md
src/cider/tasks.clj
src/cider_nrepl/main.clj

First step towards the new cider nrepl integration.

Add a simple nrepl-server task in cider.tasks

---

src/cider/nrepl/middleware/util/cljs.clj

CIDER injects cider/piggieback automatically now while some users are
still on cemerick/piggieback. The result is that this will always
return true since cider/piggieback is on the classpath.
Notably, shadow-cljs fakes a cemerick/piggieback and places the
compiler environment there for cider-nrepl. But we see the injected
cider/piggieback and so look for the cljs compiler environment there
rather than in cemerick.
see https://github.com/clojure-emacs/cider/issues/2305

Check for cemerick/piggieback and fall back to cider/piggieback

---

src/cider/tasks.clj
src/cider_nrepl/main.clj

- revert `cider.nrepl/init` such that it takes a vector of middlewares
- have `cider.nrepl/init` pass a map of arguments to `start-nrepl`
- tweak cider nrepl boot task to pass a map to `start-nrepl` directly
- set defaults for `port` and `bind` to keep `nrepl-server` happy

Proposed fix for #537

---

src/cider/tasks.clj
src/cider_nrepl/main.clj
test/clj/cider/nrepl/main_test.clj

My fix yesterday was not properly tested - I started nREPL from the command line, but I didn't attempt to exercise it with messages. As a result, I missed the fact I was setting passing the middleware as the handler, which kept things just as broken.
This PR contains a fix for that problem, plus a new test ns `cider.nrepl.main-test` that exercises the `start-nrepl` function by passing it a variety of valid and invalid option maps. The tests go as far as checking that two `:op "clone"` messages can be exchanged before declaring success.
On my local machine I saw a test failure in a totally unrelated part of the code, `test-sum-types-is-base64`, which I'm assuming is an artifact of my local environment and not something that will come up in the PR tests.

Actually fix #537

---

README.md
project.clj
src/cider/nrepl.clj
src/cider/nrepl/middleware/content_type.clj
src/cider/nrepl/middleware/debug.clj
src/cider/nrepl/middleware/inspect.clj
src/cider/nrepl/middleware/out.clj
src/cider/nrepl/middleware/pprint.clj
src/cider/nrepl/middleware/profile.clj
src/cider/nrepl/middleware/refresh.clj
src/cider/nrepl/middleware/slurp.clj
src/cider/nrepl/middleware/stacktrace.clj
src/cider/nrepl/middleware/test.clj
src/cider/nrepl/middleware/track_state.clj
src/cider/nrepl/middleware/util/error_handling.clj
src/cider/nrepl/middleware/util/nrepl.clj
src/cider/nrepl/middleware/version.clj
src/cider/nrepl/version.clj
src/cider_nrepl/main.clj
test/clj/cider/nrepl/main_test.clj
test/clj/cider/nrepl/middleware/debug_integration_test.clj
test/clj/cider/nrepl/middleware/debug_test.clj
test/clj/cider/nrepl/middleware/track_state_test.clj
test/cljs/cider/nrepl/piggieback_test.clj
test/common/cider/nrepl/test/server.clj
test/common/cider/nrepl/test_session.clj
test/common/cider/nrepl/test_transport.clj
test/smoketest/project.clj
test/smoketest/src/smoketest/core.clj

An initial stab at updating the middleware for nREPL 0.4. 
That's going to be part of the 0.19 release (or at least that's the current plan). 
Any volunteers to test with using https://github.com/nrepl/lein-nrepl? (use `lein install` to build the artefact locally)

Migrate to nREPL 0.4

---

README.md
deps.edn

Specifically this will enable: "clojure -A:cider-clj" and its ClojureScript
cousin.
---
once a PR is merged, but **only** if the CI build is green.

Add deps.edn for convenient command line launchers

---

CHANGELOG.md
src/cider/nrepl/middleware/test.clj
test/clj/cider/nrepl/middleware/test_filter_tests.clj
test/clj/cider/nrepl/middleware/test_test.clj

This PR fixes [cider issue 2449](https://github.com/clojure-emacs/cider/issues/2449) by making sure test documentation messages are always returned as strings.

Always return test documentation messages as strings

---

project.clj
src/cider/nrepl/middleware/debug.clj
test/clj/cider/nrepl/middleware/debug_integration_test.clj
test/clj/cider/nrepl/middleware/debug_test.clj

Two changes:
- debugger forms are now localized in the sense that STATE__ is inserted where the reader form is located and not around the entire defun. Besides fixing non-closure situations as in #544 it is' likely to be useful in core-async contexts (macros with &env) for which there are a few issues open. Still have to check those.
- implement a notion of a debugger session and build on top of it to fix a range of "continue" issues 
There are now two `continue` commands, one local which stops on next `#dbg` or `#break` readers, and one global which behaves like the old `continue`. First one is now on `c` and the global on is on `C`. 
I want to fix a few more debugger related issues but it seems wise to push these changes first so that people could start testing immediately.

Debugger fixes

---

CHANGELOG.md
src/cider/nrepl.clj
src/cider/nrepl/middleware/format.clj
test/clj/cider/nrepl/middleware/format_test.clj

Update `format-code` op to call `cljfmt.core/reformat-string` with config option.
* https://github.com/weavejester/cljfmt#configuration

Update format-code op to call cljfmt with option

---

.travis.yml
project.clj

This version of Compliment fixes the class name completion on JDK9+.

Bump compliment to 0.3.7-SNAPSHOT

---

CHANGELOG.md
README.md
src/cider/nrepl.clj
src/cider/nrepl/middleware/ns.clj
test/clj/cider/nrepl/middleware/ns_test.clj

Add `ns-aliases` op to the ns middleware.

Add ns-aliases op

---

project.clj

This is necessary in new Clojure 1.10 releases, see
https://github.com/brandonbloom/fipp/issues/52.

Bump fipp so that we silent Clojure 1.10 warnings

---

src/cider/nrepl/middleware/util/instrument.clj
test/clj/cider/nrepl/middleware/debug_integration_test.clj
test/clj/cider/nrepl/middleware/util/instrument_test.clj

There is one side-effect of #552 that I have noticed so far  - functions with recur in them cannot be debugged.  For example instrumenting the following form will throw
```cl
#dbg
(defn foo [a]
(if (pos? a)
(recur (dec a))
:done))
```
The reason for this is that instrumentation doesn't instrument forms containing recur unless in a `loop*` form. I am adding `fn*` to the relevant check because `fn*` is also a target of `recur`. This issue went unnoticed because it could occur only for local let bound functions before, but with localized debugger implementation it occurs with top level defn as well. 
@Malabarba, do you still remember why `contains-recur?` doesn't provision for fn* target? Was there a special reason for that? I have been testing this patch for 2 weeks now and haven't noticed …

Fix instrumentation of recursive functions

---

src/cider/nrepl/middleware/out.clj

Although the `forking-writer` *should be* a `PrintWriter`, in practice we've
seen that a `BufferedWriter` can be returned. This led to the error:
>java.lang.ClassCastException: java.io.BufferedWriter cannot be cast to
java.io.PrintWriter
These types of errors are avoided by using the base class `Writer` of the
`BufferedWriter` and `PrintWriter`, just as is done in the rest of this file.

[Fix #570] Use base class of different writers

---

CHANGELOG.md
src/cider/nrepl/middleware/util/error_handling.clj
test/clj/cider/nrepl/middleware/util/error_handling_test.clj

This PR adds a `:root-ex` key to the error summary that contains the classname of the root cause.

[Fix #225] Add :root-ex to error summary

---

deps.edn

Just a simple PR to bump the fipp version regarding [this PR](https://github.com/brandonbloom/fipp/commit/1d5b74a3cd384b2673c9f45c204838bab20ac7b3).
The latest fipp version includes updates to rrb-vector, which now works nicely with JDK11 rather than throwing weird errors.

Bumping fipp deps for JDK11 support

---

CHANGELOG.md
src/cider/nrepl/middleware/inspect.clj
test/clj/cider/nrepl/middleware/inspect_test.clj

**The problem**
If you inspect an expression that throws an exception (e.g. `(/ 1 0)`), the inspector silently discards the exception as if nothing has happened. This is annoying.
**Why?**
Cider already has machinery for things like that, e.g. if macroexpansion throws an error, it will be displayed in a special cider middleware error buffer. That is implemented by macroexpansion middleware using `with-safe-transport` which, in the case of error, returns a message with status `[:done :macroexpansion-error]`. On the Emacs side, Cider's `cider-nrepl-send-sync-request` listens to `:done` events, and if there's an error status after it the error buffer will be raised.
Why doesn't it work for inspector? Because at some point (#164) the inspector has been changed from having its own middleware …

Fix inspector silently doing nothing if eval errored

---

.travis.yml
Makefile
project.clj
test/common/cider/nrepl/test_session.clj

These are all changes I made in the context of #569 that are not directly related to fixing tests (although some are necessary prerequisites for what follows, e.g. the min/max-clj-version fixes).
I'll make a separate PR with the testing fixes once this is merged.
----
Before this Leiningen middleware was being added implicitly, but in the latest
Leiningen this causes a warning. Configure it explicitly instead, and disable
Leiningen's support for implicit middleware.
----
To be able to account for subtle differences between Clojure versions we have
metadata based filters. The min-clojure-version filter however no longer worked
correctly because Clojure 1.10 would sort before 1.9. Fixed this by adding
explicit version parsing, and also added a max-clj-version filter.
----
Many tests make …

Test repl setup improvements

---

.travis.yml
project.clj
src/cider/nrepl/middleware/macroexpand.clj
src/cider/nrepl/middleware/util/cljs.clj
test/clj/cider/nrepl/middleware/apropos_test.clj
test/clj/cider/nrepl/middleware/inspect_test.clj
test/clj/cider/nrepl/middleware/pprint_test.clj
test/clj/cider/nrepl/middleware/stacktrace_test.clj
test/smoketest/project.clj
test/smoketest/src/smoketest/core.clj

This branch contains the "real" fixes that came out of #569. It also adds Clojure 1.10 to the build matrix.
See individual commits for exact changes. Unless #578 gets in the way this should go green now :crossed_fingers:

CI test fixes

---

project.clj

-  add excluded namespaces
This is not done yet, but with three excluded ns's, linting passes without exceptions, but with errors.
One of the exceptions (thrown from `test-sessions` is a bug in eastwood (https://github.com/jonase/eastwood/issues/306)
The two others might be bugs in eastwood, I don't know.
I'll leave this here for now, and work a bit more on it, so please don't merge yet.

[Fix #575] Upgrade to Eastwood 0.3.4

---

test/clj/cider/nrepl/middleware/debug_integration_test.clj

These tests use special `--->` and `<---` macros to sketch out an interaction
with the debugger, but the `<---` macro (nrepl-recv) did not account for the
possibility of a timeout. A timeout would result in receiving a `nil` message,
which was then treated as an empty map as far as assertions are concerned.
When this happened the actual and expected messages would get out of sync,
causing all future assertions in the same test var to also fail.
This commit increases the timeout from 200 to 500 ms, and throws an exception
when a timeout does occur.

Increase timeout in debug-integration-test, fail loudly upon timeout

---

.gitignore
Makefile
test/cljs/cider/nrepl/piggieback_test.clj

Fixes #578.
When I added the CLJS tests, Nashorn was unavailable on JDK 7 – but we no longer support that. Nashorn is now deprecated as of JDK 11, the suggested alternative being Graal, but that is unavailable on JDK 8 which we do still support. Additionally `cljs.repl.graaljs` was only added in ClojureScript 1.10.439.
For now: just use Nashorn; if it's removed in some future JDK version then what we do will depend on which JDKs/CLJS versions we still support at that time.

Use Nashorn for CLJS tests

---

src/cider_nrepl/plugin.clj
test/common/cider_nrepl/plugin_test.clj

Check out [nippy](https://github.com/ptaoussanis/nippy) and jack in. You are greeted with:
```shell
;; Clojure 1.10.0, Java 1.8.0_201                ;; <----------------- note 1.10.0
;;     Docs: (doc function-name)
;;           (find-doc part-of-name)
;;   Source: (source function-name)
;;  Javadoc: (javadoc java-object-or-class)
;;     Exit: <C-c C-q>
;;  Results: Stored in vars *1, *2, *3, an exception in *e;
WARNING: CIDER requires cider-nrepl to be fully functional. Many things will not work without it!
More information.
user> 
```
If you run the start up command on the shell you are greeted with:
```bash
[dan@fedora nippy]$ /home/dan/bin/lein update-in :dependencies conj \[nrepl\ \"0.6.0\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \.21.2-SNAPSHOT\"\] -- repl :headless :host …
```

Allow for multiple Clojures when checking Clojure version

---

.travis.yml
Makefile
README.md
project.clj

mranderson 0.5.x specific config added to the project file as
well. **Resolved tree** mode is used. This means that
mranderson works with a resolved dependency tree and does not create a
deeply nested directory structure, only adds prefixes to all
dependencies. Handles all depedendencies as first level ones and
processes them in a topological order.
Add project prefix in the project file for mranderson, also some
config for **unresolved tree** if that would get used in the near
future.
Breaking changes in mranderson are followed up in Makefile and README

Upgrade mranderson to 0.5.0

---

CHANGELOG.md
src/cider/nrepl.clj
src/cider/nrepl/middleware/ns.clj
test/clj/cider/nrepl/middleware/ns_test.clj
test/cljs/cider/nrepl/middleware/cljs_ns_test.clj

Add a option for filtering vars to the ns-vars middleware

---

src/cider_nrepl/plugin.clj
test/clj/cider/nrepl/plugin_test.clj

When using dependency supplying modules such as `lein-modules`,
by the time cider-nrepl does its version check it has no indication
of version.
In this case, the code throws leaving no chance to the REPL to
be spun up.
When versions are unavailable, assume the project knows what it
is doing instead and discard it from the version check altogether.

plugin: ensure there is a version to check to begin with

---

Makefile
README.md
project.clj
src/cider/nrepl/middleware/debug.clj
src/cider/nrepl/middleware/info.clj
src/cider/nrepl/middleware/macroexpand.clj
src/cider/nrepl/middleware/ns.clj
src/cider/nrepl/middleware/stacktrace.clj

This patch copies the leftover "business logic" from the `info` middleware to
the `orchard` `info` function. This will make the `info` function in `orchard`
self-contained, which is easier to test and more portable (one could use
`orchard` without the `nrepl` protocol for instance - say for a Language Server
Protocol implementation).
- [] All tests are passing

Move leftover code from the info middleware to orchard

---

CHANGELOG.md
src/cider/nrepl/middleware/apropos.clj
test/clj/cider/nrepl/middleware/apropos_test.clj

The required structure for the 'query/var' function is `{:var-query
{:ns-query {...}}`. The older implementation did not grab those
keywords from the cider message and put them at the correct
level. they were left top level and then missed by the
`query/namespace` function.
In addition to this, there was a bug in orchard which had the wrong
prefix for inlined deps so these were not omitted in _2_ places: both
in the client-side specification of which namespaces to ignore and
orchard's own mechanism to elide cider's internal namespaces.
See related:
- orchard https://github.com/clojure-emacs/orchard/pull/59/
- CIDER
once a PR is merged, but …

Ensure ns-query map is built correctly

---

test/clj/cider/nrepl/middleware/info_test.clj

Tests response from javadoc. Failing on java 11 expecting
"https://docs.oracle.com/javase" for both java 8 and 11. On 11 have
the following response:
Clearly fine just bad prefix
```
{:javadoc
"https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java.base/java/lang/StringBuilder.html#capacity()",
:throws [],
:file [],
:arglists-str "[this]",
:argtypes [],
:member "capacity",
:modifiers "#{:public :bridge :synthetic}",
:status #{"done"},
:id "5174fd6d-4f65-4524-babb-07bc2ef2dcb3",
:class "java.lang.StringBuilder",
:returns "int",
:session #{"b85884cb-3503-428c-8123-5c970dd08605"}}
```
once a PR is merged, but **only** if the CI build …

Fix last test failing on CI

---

CHANGELOG.md
src/cider/nrepl/middleware/track_state.clj
test/clj/cider/nrepl/middleware/track_state_test.clj

I have tried to fix an issue with some functions not being properly dynamically font-locked in ClojureScript.
As you can see in the diff, I have used the tags generated by, as far as I understand, `cljs.analyzer`. The following screen shot shows the result, as well as the tags given to the various definitions. You can see in the bottom vector the result, where of course functions are colored with green, and other values with orange.
Previously, only `fn1` and `fn5` would have been recognized as functions (and of course `comp`). As you can see, `fn7`, `fn8` and `fn8` are not recognized, but that is not something we can fix in CIDER, I guess.
I wrote made this pull request to get feedback---what do you think about this? Also, is there anything else I should do, such as adding a line in …

Fix dynamic font locking for fns defined with def in cljs

---

src/cider/nrepl/middleware/stacktrace.clj

Due to refactoring done in orchard `resource-path` function moved to
dedicated namespace `orchard.resource`
once a PR is merged, but **only** if the CI build is green.
*If you're just starting out to hack on cider-nrepl you might find
this [article](https://juxt.pro/blog/posts/nrepl.html) and the
Thanks!

Fix compilation exception

---

src/cider/nrepl/middleware/resource.clj
src/cider/nrepl/middleware/stacktrace.clj
test/clj/cider/nrepl/middleware/resource_test.clj

This patch moves the code for the resource op down into the orchard.

Move resource implementation to orchard

---

src/cider/nrepl/middleware/track_state.clj
test/clj/cider/nrepl/middleware/track_state_test.clj

I discovered that multifns have a tag I didn't account for earlier, in #622

Dynamically font lock multifns as fns in CljS

---

src/cider/nrepl/middleware/clojuredocs.clj
src/cider/nrepl/middleware/debug.clj
src/cider/nrepl/middleware/info.clj
src/cider/nrepl/middleware/ns.clj
src/cider/nrepl/middleware/resource.clj
src/cider/nrepl/middleware/stacktrace.clj
src/cider/nrepl/middleware/test.clj
src/cider/nrepl/middleware/track_state.clj
src/cider/nrepl/middleware/util.clj

The transform-value function is moved here to cider-nrepl, where it belongs, as
it seems to be mainly related to presentation only.
PR friend of https://github.com/clojure-emacs/orchard/pull/66 

Move transform-value from the orchard to cider-nrepl

---

src/cider/nrepl/middleware/ns.clj
test/clj/cider/nrepl/middleware/ns_test.clj

Fixes https://github.com/clojure-emacs/cider/issues/2681#issuecomment-520196771
Allowing cider-find-ns to open files in jars.

Properly extract jar paths in `cider.nrepl.middleware.ns/ns-path`

---

CHANGELOG.md
README.md
project.clj
src/cider/nrepl/middleware/complete.clj
test/cljs/cider/nrepl/middleware/cljs_complete_test.clj

once a PR is merged, but **only** if the CI build is green.
*If you're just starting out to hack on cider-nrepl you might find
this [article](https://juxt.pro/blog/posts/nrepl.html) and the
Thanks!

dynamic cljs completions with suitable

---

project.clj

This adds a debug var to suitable that's disabled by default which means that error reporting is suppressed.
Addresses #637.
Thanks!

bump suitable to fix #637

---

project.clj

This fixes calls to suitable when the completion context contains no
`__prefix__` (e.g. when typing the metadata of a ns like `(ns ^foo| bar.baz)`)
Thanks!

suitable upgrade to 0.2.6

---

project.clj

- nodejs would throw nullpointer exception on first completion due to repl-env
not being initialized
- [yep] The commits are consistent with our [contribution guidelines](CONTRIBUTING.md)
- [yep] All tests are passing
- [yep] The new code is not generating reflection warnings
Thanks!

bump suitable to fix #643

---

CHANGELOG.md
src/cider/nrepl/middleware/complete.clj
test/cljs/cider/nrepl/middleware/cljs_complete_test.clj

to make suitable cljs completions optional
https://github.com/clojure-emacs/cider-nrepl/issues/648

add enhanced-cljs-completion flag

---

src/cider/nrepl/middleware/test/extensions.clj
test/clj/cider/nrepl/middleware/test/extensions_test.clj

The current implementation of `=-body` evaluates the rest of the arguments to `=` before evaluating the first argument. This causes problems in the presence of side-effects.

Fix execution order for (is (= a b c))

---

src/cider/nrepl/middleware/debug.clj

Fixes https://github.com/clojure-emacs/cider/issues/2621
I'm not familiar at all with the internals of `cider-nrepl`, but having been annoyed by the above issue one too many times I decided to grep for `*print-length*` in this repo and found that simply changing these lines solved the issue. 
Perhaps there's a better way to tackle it, hopefully this PR gives a starting point :)

Respect default *print-length* and *print-level* in debugger output

---

src/cider/nrepl.clj
src/cider/nrepl/middleware/inspect.clj
test/clj/cider/nrepl/middleware/inspect_test.clj

This PR adds inspect-def-current-value that will enable cider-inspector to define a var in your current namespace with a given name and current inspector value.

Add inspect-def-current-value to inspect middleware

---

CHANGELOG.md
src/cider/nrepl/middleware/debug.clj
test/clj/cider/nrepl/middleware/debug_integration_test.clj

Note: This is a breaking change that sends debug commands to the client as an unsorted
list of command names without key mapping information, as a means of separating
concerns.
Quick draft of the changes suggested in https://github.com/clojure-emacs/cider/pull/2731
If everything looks alright I'll go ahead with adding changelog notes and tests

Change representation of debug-commands to a set of command names

---

CHANGELOG.md
src/cider/nrepl/middleware/debug.clj

Credit goes to @alexander-yakushev in #613 :)

Make inspect command work on current expression, add inspect-prompt 

---

CHANGELOG.md
src/cider/nrepl/middleware/info.clj
test/clj/cider/nrepl/middleware/info_test.clj

Currently, the meta data for protocol method without docstring has a `nil` value for `:doc` key.
```clj
(defn foo [])
(defn bar "..." [])
(defprotocol Dummy
(hello [this])
(world [this] "..."))
(meta #'foo)   ; not containing `:doc`
(meta #'bar)   ; containing `:doc`
(meta #'hello) ; containing `:doc`, but nil
(meta #'world) ; containing `:doc`
```
The `nil` value is treated as a list by nrepl/bencode, so `info` op returns a empty list as a docstring for protocol method.
https://github.com/nrepl/bencode/blob/v1.0.0/src/bencode/core.clj#L324
E.g. `info` response for `hello`
```sh
d12:arglists-str6:[this]3:docle4:file47:file:/.../core.clj4:linei7e4:name5:hello2:ns8:foo.core8:protocol16:#'foo.core/Dummy7:session36:3b4401ac-a962-43b1-8fbc-1c17d
b0477346:statusl4:doneee
```
Is this an expected …

Fix info op not to return nil as a document for protocl

---

CHANGELOG.md
src/cider/nrepl/middleware/debug.clj
test/clj/cider/nrepl/middleware/debug_integration_test.clj

The :continue-all command was previously not
ignoring conditional breakpoints as in the
following code.
(for [i (range 10)]
#dbg ^{:break/when (even? i)}
(inc i))
Fixes #656.

Fix continue-all in conditional break.

---

CHANGELOG.md
src/cider/nrepl/middleware/util/instrument.clj
test/clj/cider/nrepl/middleware/util/instrument_test.clj

Case expands the non-default branches into a map. This can be seen
when evaluating the following code:
```clj 
(walk/macroexpand-all '(case i
10 (recur (inc i))
:halt))
```
The `contains-recur?` function did so far not take that into account.
I was able to run tests for 1.9 and 1.10. 1.9 had 1 failure non related to my code and 1.10 none.
I was unable to run the tests for 1.8 because of some leiningen issue.
This should be fixing [cider#2772](https://github.com/clojure-emacs/cider/issues/2772)

Fix non-recognized `recur` inside `case` in the debugger.  

---

CHANGELOG.md
src/cider/nrepl/middleware/util/instrument.clj
test/clj/cider/nrepl/middleware/debug_integration_test.clj

Map literal instrumentation was relying on some heuristic before.
We use Clojures underlying array-map implementation for small map
literals and fall back to a sorted order of keys if that is not the
case. If this fails as well we simply instrument only the values of
the map in the order they appear in a sequential pass.
This fixes https://github.com/clojure-emacs/cider/issues/2773 for small maps at least.

Fix instrumentation of small map literals. Minor doc updates.

---

CHANGELOG.md
project.clj
src/cider/nrepl/middleware/complete.clj
src/cider/nrepl/middleware/track_state.clj
test/cljs/cider/nrepl/middleware/cljs_complete_test.clj

This patch adds the new feature to `cider-nrepl` and also deprecates
`cljs-tooling`.
It depends on the new version of `clj-suitable` and `compliment`.
Thanks!

Integrate the new suitable ClojureScript completion

---

CHANGELOG.md
src/cider/nrepl/middleware/apropos.clj
test/clj/cider/nrepl/middleware/apropos_test.clj

This is a change as described in https://github.com/clojure-emacs/cider-nrepl/issues/530.
In `apropos` middleware, if no `query` is passed in the message then a redundant regex is formed.
This is because there is no condition that checks whether the value exists before constructing the regex.
I have added such a check. I have also added a test for this specific case.

Add a check in apropos var-query-map

---

CHANGELOG.md
src/cider/nrepl/middleware/undef.clj
test/clj/cider/nrepl/middleware/undef_test.clj

See https://github.com/clojure-emacs/cider/issues/2814.
The current cider.el frontend sends `undef` op with `ns` as the current ns and `symbol` as a possibly ns-qualified var, which this PR interprets as unmapping the symbol from the corresponding other namespace.
For some reason running tests locally with `make test` turns up many failures in `cider.nrepl.middleware.debug-integration-test` which seem to be unrelated to the changes in this PR.

Extend undef op to work on fully qualified symbols

---

CHANGELOG.md
src/cider/nrepl/middleware/slurp.clj
test/clj/cider/nrepl/middleware/slurp_test.clj

Fix some issues in `slurp` middleware as seen in https://github.com/clojure-emacs/cider-nrepl/issues/534

Fix NPE and add isDirectory check in slurp

---

CHANGELOG.md
src/cider/nrepl/middleware/util/instrument.clj
test/clj/cider/nrepl/middleware/util/instrument_test.clj

--- 
Fix for https://github.com/clojure-emacs/cider-nrepl/issues/671
Instrumentation for dot special forms of type `(. clojure.lang.Numers (add 1 x))` fails. There is no breakpoint set for `x`.
This PR fixes this so that the breakpoints are set inside the dot special form.

Fix instrument for a dot special form case

---

README.md

Took me a moment to realize these are the same project, clj-suitable

fix double-reference to clj-suitable in the README

---

CHANGELOG.md
src/cider/nrepl/middleware/debug.clj
test/clj/cider/nrepl/middleware/debug_integration_test.clj

Fixes https://github.com/clojure-emacs/cider/issues/2852

Remove workaround for converting column numbers

---

CHANGELOG.md
src/cider/nrepl/middleware/classpath.clj
test/clj/cider/nrepl/middleware/classpath_test.clj

Not all urls on a classpath are necessarily files. Eg. spring boot
adds "jar:file:..." urls
This can only be merged after https://github.com/clojure-emacs/orchard/commit/9fe7a70e7ea0e7984317aa80634367ff5ca327e9 was released.
This is at least related to https://github.com/clojure-emacs/orchard/pull/83

Filter non file urls from classpath response

---

src/cider/nrepl/middleware/debug.clj

Fix remaining reflection warnings on repl start.
please consider merging https://github.com/clojure-emacs/orchard/pull/101 as well and release them together.
Tests are failing on master ;-(
---
- [FAIL] All tests are passing
Thanks!

Remove reflection warnings

---

project.clj

This brings the reflection warnings fixes made in compliment with the following PR: https://github.com/alexander-yakushev/compliment/pull/75
---
- [FAIL] All tests are passing - same failure as `master`

update compliment dependency

---

CHANGELOG.md
src/cider/nrepl/middleware/test.clj
test/clj/cider/nrepl/middleware/test_test.clj

This PR fixes test reporting for libraries that rely on custom print logic that can be added by `(defmethod print-method ,,,`, such as `matcher-combinators`: https://github.com/clojure-emacs/cider/issues/2901#issuecomment-723312712

Support custom print-methods in test reports

---

CHANGELOG.md
src/cider/nrepl.clj

Hi,
This is an attempt to fix issue around delayed middleware loading.
The relevant discussion is present at https://github.com/clojure-emacs/cider-nrepl/issues/533 
Instead of adding the handler delay to the `delayed-handlers` atom in the macro, this takes care of adding
it in the atom through a function. 
Fixes:
https://github.com/clojure-emacs/cider-nrepl/issues/447
https://github.com/clojure-emacs/cider-nrepl/issues/533
https://github.com/clojure-emacs/cider-nrepl/issues/657

Fix delayed middleware loading issue

---

.clj-kondo/config.edn
project.clj
src/cider/nrepl/middleware/complete.clj
src/cider/nrepl/middleware/slurp.clj
src/cider/nrepl/print_method.clj
test/clj/cider/nrepl/middleware/slurp_test.clj
test/cljs/cider/nrepl/middleware/cljs_complete_test.clj

Fixes the build by:
* "soft-reverting" the `suitable` removal
* it's now only enabled in test environments
* that way, the tests will pass again, while not affecting end users
* Disabling a specific clj-kondo pass for now
* https://github.com/clj-kondo/clj-kondo/issues/1247
* Fixing a broken test related to `slurp`
* I can't make a super precise analyis but a few things seemed off:
* `(t/is (= ["application/octet-stream" {}]))` **always** passes (there's just one hand to the `=`)
* The result of hitting `https://clojure.org/no-such-page` is subject to change as it's a page outside CIDER's control
* Anyway, the broken test revealed (?) that hitting a 404 page would throw an exception
* It seems a good thing to handle that exception
* Unknown: is the caught result usable for end users? …

Fix the build

---

.circleci/config.yml
Makefile
project.clj

Running `curl | bash` didn't seem exactly ideal, and also it seems a good idea to run a stable, fixed version.
Finally it's also good to stick to vanilla JVM clojure, removing the possibility of graalvm doing something funny.
Green build in my personal account

Run clj-kondo by a more stable means

---

CHANGELOG.md
src/cider/nrepl/middleware/debug.clj

Fixes #689 
In the `break` function, we reset the `:skip` in `STATE` when the debuggable function is called again. 
This is checked using the `coor` as follows -- 
```clojure
(if-let [first-coor @(:session-id STATE__)]
(when (= first-coor coor)
(reset! (:skip STATE__) false)
(reset! (:session-id STATE__) coor))
```
But in case of functions called via HTTP -- 
- We skip breakpoints not using the `STATE__` but by setting `*skip-breaks*` atom as `{:mode :all}`. 
- Hence along with resetting `STATE__` on function being called again, we also need to reset the `*skip-breaks*` atom. 
This fixes the behavior of `:continue-all` and `:quit` commands for functions being called via HTTP.

Fix debugger quit for http handler functions

---

.circleci/config.yml
CHANGELOG.md
project.clj
src/cider/nrepl.clj
src/cider/nrepl/middleware/inspect.clj
test/clj/cider/nrepl/middleware/inspect_test.clj

TODO: adjust cider/orchard version when published
The limits after which the inspector truncates collection members are now
configurable. Previously they were hardcoded to 5 and 150 for collection and
atom (non-collection) members.
---------------------------------
This continues the work in https://github.com/clojure-emacs/orchard/pull/111 and needs to be updated with the right orchard version number before it can merge.
---------------------------------

[Inspector] Configure truncation limits

---

CHANGELOG.md
doc/modules/ROOT/pages/nrepl-api/ops.adoc
src/cider/nrepl.clj
src/cider/nrepl/middleware/undef.clj
test/clj/cider/nrepl/middleware/undef_test.clj

The purpose of this op is to support a complete "reload" of a file or `ns` form in Cider (C-u M-x cider-load-file) and other clients.
Which is sometimes necessary when you have conflicting aliases or old/renamed vars sticking around in the REPL state.
----
Thanks!

Add undef-all op

---

CHANGELOG.md
project.clj
src/cider/nrepl/middleware/debug.clj
src/cider/nrepl/middleware/stacktrace.clj
src/cider/nrepl/middleware/test.clj
test/clj/cider/nrepl/middleware/stacktrace_test.clj

Prior to this fix, the cider-stacktrace "project-only" filter could be easily broken in presence of user.clj/dev.clj, because those single-segment namespaces would break the commonality between all other namespaces.
Also, performance is improved. The old `(map vector common ns)` created two vectors of chars, an operation to be repeated once per ns in the project. This is memory-hungry, even more so with the related `take-while` which is lazy.
An approach based on `reduce`/`reduce-kv`/`reduced` is introduced instead.
Parallelism is introduced as well.
Finally, `def directory-namespaces` is changed for `defn directory-namespaces`. The set of directory namespaces is always subject to change, so one has to ensure up-to-date accuracy on every invocation.
Accordingly, I had to perform …

Make `stacktrace/ns-common-prefix` work in presence of user.clj files

---

CHANGELOG.md
src/cider/nrepl/middleware/test.clj
test/clj/cider/nrepl/middleware/test_test.clj

This allows users to attach arbitrary functionality when tests fail due to an exception.
For example, I used this to add an Expound-backed `println` for exceptions that were caused by Spec failures.
...While CIDER already prints Spec failures nicely via an Emacs UI, not all cider-nrepl clients necessarily have such an UI.
One might also appreciate a println with Expound's format, which is familiar for many, and will be consistent with printlns placed elsewhere in a given codebase.

Introduce `middleware.test/*test-error-handler*`

---

.circleci/config.yml
test/clj/cider/nrepl/print_method_test.clj

* CI: remove repo cache
* Rationale: https://github.com/clojure-emacs/refactor-nrepl/pull/325#issuecomment-909417615
* Refine `test_code` cache key
* Inspired by refactor-nrepl's setup, it had a problem that was solved this way.
* Fix flaky `print-idrefs-test`
* Closes https://github.com/clojure-emacs/cider-nrepl/issues/706

Improve build stability

---

CHANGELOG.md
src/cider/nrepl.clj

When loading CIDER middleware via the sideloader we need to make sure that extra
namespaces that are loaded later are also requested via the sideloader. The
original sideloader already provided a macro for
this (with-session-classloader), we just need to use it. This does mean that now
all our middlewares need to depend on the session middleware.
(see an earlier comment hinting at the fact this would still need to happen: https://github.com/nrepl/nrepl/pull/185#issuecomment-624317912)
Part of: https://github.com/clojure-emacs/cider/issues/3037

Use session classloader when loading deferred middleware

---

project.clj
src/cider/nrepl/middleware/out.clj

> Fixes https://github.com/clojure-emacs/cider-nrepl/issues/716
I saw following error messages when starting REPL.
```
;; on `*nrepl-server ... *` buffer
Exception: java.lang.StackOverflowError thrown from the UncaughtExceptionHandler in thread "Timer-0"
Exception: java.lang.StackOverflowError thrown from the UncaughtExceptionHandler in thread "Timer-1"
```
It was introduced at 1007408 commit.
```clojure
;; new
(defn original-output
"Store the values of the original output streams so we can refer to them."
^PrintWriter
[k]
({:out *out*
:err *err*} k))
;; old
(def original-output
"Store the values of the original output streams so we can refer to them."
{:out *out*
:err *err*})
```
`original-output` in `cider.nrepl.middleware.out` was changed to the function from the variable. 
If you …

Fix stack overflow error in cider.nrepl.middleware.out

---

src/cider/nrepl/middleware/test.clj
test/clj/cider/nrepl/middleware/test_test.clj

Currently, when a clojure test assertion fails with an exception, the
:line reported is for the start of the test function.
This changes the reported line to the first line of any function within
the test function.

fix: report test assertion line on exception

---

CHANGELOG.md
project.clj
src/cider/nrepl/middleware/out.clj
test/clj/cider/nrepl/middleware/out_test.clj

Remove reflection to improve speed and reduce garbage creation.
- [] You've updated the README (if adding/changing middleware)

fix: remove reflection in forking-printer

---

src/cider/nrepl/middleware/out.clj
test/clj/cider/nrepl/middleware/out_test.clj

Output to the original output outside of the with-out-binding loop.

fix: remove the possible duplicate output introduced in a052dd8

---

src/cider/nrepl/middleware/out.clj

The binding is not used within the body expressions, and costs a thread
local binding, producing garbage.  This changes ensures print-stream
produces no memory garbage.
-------
Thanks!

chore: remove unnecessary binding of current message

---

CHANGELOG.md
project.clj
src/cider/nrepl/middleware/content_type.clj
src/cider/nrepl/middleware/inspect.clj
src/cider/nrepl/middleware/test/extensions.clj
src/cider/nrepl/middleware/track_state.clj
test/clj/cider/nrepl/middleware/test/extensions_test.clj

* Unwrap lists for `:actual` in `=` arity 2
* Use traditional clojure.test notation for `:actual` in `=` arity 3+
This is clearly reflected in the included tests.
Fixes https://github.com/clojure-emacs/cider-nrepl/issues/735

Refine `=-body` behavior

---

.circleci/config.yml
.clj-kondo/config.edn
CHANGELOG.md
Makefile
src/cider/nrepl/middleware/macroexpand.clj
tools-deps-testing/deps.edn
tools-deps-testing/example.clj
tools-deps-testing/macroexpand_tools_deps_test.clj

Fixes https://github.com/clojure-emacs/cider-nrepl/issues/721
This issue is best summarized at https://github.com/clojure-emacs/cider-nrepl/issues/721#issuecomment-982690676
I was only able to reproduce it with tools.deps (just like OP), which is why a tools.deps-based integration test is proposed.
I verified that the test would fail the build if the fix is reverted: https://app.circleci.com/pipelines/github/clojure-emacs/cider-nrepl/500/workflows/bf930f3b-3deb-4c75-9f03-aa8c30ebca49

cider-macroexpand: Bind `LOADER` if unbound

---

src/cider/nrepl/middleware/out.clj
test/clj/cider/nrepl/middleware/out_test.clj

Replace the per output-stream Timer instance with a single scheduled
thread pool executor with a single thread.
- Removes the need for a proxy object on every print-stream.
- Executor service is generally preferred over Timer.
- The thread is named so its purpose is apparent.
-------

chore: use single executor service instead of timer per stream

---

.clj-kondo/config.edn
.clj-kondo/hooks/core.clj

Allow clj-kondo to understand the with-out-binding form, so linters
still get applied to it.

chore: add clj-kondo rewrite hook for with-out-binding

---

CHANGELOG.md
doc/modules/ROOT/pages/nrepl-api/ops.adoc
doc/modules/ROOT/pages/nrepl-api/supplied_middleware.adoc
src/cider/nrepl.clj
src/cider/nrepl/middleware/content_type.clj
test/clj/cider/nrepl/middleware/content_type_test.clj

Duplicate of #548 to see if CircleCI is happier this way.
Thanks!

Content-type dispatch via multimethod

---

CHANGELOG.md
project.clj

Upgrade [Orchard](https://github.com/clojure-emacs/orchard/blob/v0.9.0/CHANGELOG.md#090-2022-01-10), [nrepl](https://github.com/nrepl/nrepl/blob/0.9.0/CHANGELOG.md#090-2021-12-12), tools.namespace, fipp.

Upgrade Orchard, nrepl

---

CHANGELOG.md
project.clj

https://github.com/clojure-emacs/orchard/blob/v0.9.1/CHANGELOG.md#091-2022-01-17
⚠️ nrepl also deserves an upgrade in this batch, it's pending on https://github.com/nrepl/nrepl/pull/265

Upgrade Orchard

---

CHANGELOG.md
project.clj

Mostly a dummy change to test out the new [release setup](https://github.com/clojure-emacs/cider-nrepl/pull/745).

Upgrade `tools.trace`

---

CHANGELOG.md
src/cider/nrepl/middleware/undef.clj
test/clj/cider/nrepl/middleware/undef_test.clj

See https://github.com/clojure-emacs/cider/issues/3194

undef-all: skip unmapping of default imports

---

CHANGELOG.md
project.clj

Build should be green now as puget/arrangement no longer use the workaround that made mranderson upset.

Bump `puget`

---

CHANGELOG.md
doc/modules/ROOT/pages/nrepl-api/ops.adoc
src/cider/nrepl.clj

I missed that the NREPL op documentation is generated from the descriptors. I moved the documentation there, and generated the docs with `lein docs`. I also updated the changelog entry, which I previously missed.
---
Thanks!

Generate ops

---

CHANGELOG.md
src/cider/nrepl/middleware/complete.clj
test/cljs/cider/nrepl/middleware/cljs_complete_test.clj

When editing a ClojureScript file, cider-nrepl doesn't offer any local binding names (the function name and argument names if inside the function, the let-like block bindings if inside a let-like block, etc.) as completion candidates, like it does when editing a Clojure file.
The root of the problem is that
`cider.nrepl.middleware.complete/cljs-sources` only includes `::suitable-sources/cljs-source` as a possible source. And `suitable` doesn't perform any local binding analysis.
Given that the local binding analysis done in
`compliment.sources.local-bindings` namespace doesn't perform any evaluation or execution of the context form (thus, it is independent of the actual host platform differences), we can use that same source for ClojureScript local bindings completion.
[Closes: #766] …

Complete local bindings for ClojureScript files

---

src/cider/nrepl/middleware/debug.clj
src/data_readers.clj

I added malabarba's idea for simple break on exception from here https://github.com/clojure-emacs/cider/issues/2754#issuecomment-563189438
Basically when you run something and get an exception, you can click in the error buffer the location in your source closest to the top of the stacktrace, it takes you to the source location, you add a `#exc` before the form, and rerun whatever caused the exception, now the debugger will break there showing the exception and you can inspect local variables, eval stuff in the local context etc.
Of course this is basic and limited, as noted in that issue:
> Wrapping the point of exception in a try-form and setting breakpoint on except. Kind of works, but only (1) in your own source code (not on exceptions thrown in libraries) (2) only after you known the …

add #exc reader to break on exception

---

CHANGELOG.md
doc/modules/ROOT/pages/hacking.adoc
src/cider/nrepl/middleware/debug.clj
src/cider/nrepl/middleware/util/instrument.clj
src/data_readers.clj
test/clj/cider/nrepl/middleware/content_type_test.clj
test/clj/cider/nrepl/middleware/debug_integration_test.clj
test/clj/cider/nrepl/middleware/info_test.clj

Continuing the discussion from #769, and marking this as a draft PR as I'm unsure about some of these changes, in particular the hack with the `STATE__` anaphor to get a `:caught-msg` key into the response.
Re. naming, should I change the tags to `#break!` and `#dbg!` as previously suggested, or try and implement as metadata keys? Note that currently it doesn't seem possible to combine `:break/when` functionality with the new on-exception debugging.
There are some changes here related to overriding various heuristics on what is "interesting", commit c5f3084ffccd4e498d614cb21fa149a21208b237 in particular makes it so you can actually tag a vector / map with #break, something I've always been annoyed by:
```clj
(into {}
(for [x (range 5)]
#break
[(char (+ 97 x)) (inc x)]))
```
Also I haven't …

Debugger tweaks

---

.clj-kondo/config.edn
CHANGELOG.md
doc/modules/ROOT/pages/nrepl-api/supplied_middleware.adoc
doc/modules/ROOT/pages/usage.adoc
project.clj
src/cider/nrepl.clj
src/cider/nrepl/middleware.clj
src/cider/nrepl/middleware/log.clj
test/clj/cider/nrepl/middleware/log_test.clj
test/resources/logback-test.xml
test/resources/logging.properties

This PR adds the CIDER log middleware, now with logjam extracted into its own repository.
The initial PR was this one:
https://github.com/clojure-emacs/cider-nrepl/pull/773
And this for the CIDER side:
https://github.com/clojure-emacs/cider/pull/3352
Thanks!

Add CIDER log middleware

---

CHANGELOG.md
doc/modules/ROOT/pages/nrepl-api/ops.adoc
maint/cider/nrepl/impl/docs.clj
project.clj
src/cider/nrepl.clj
src/cider/nrepl/middleware/test.clj
test/clj/cider/nrepl/middleware/test_test.clj
test/resources/failing_test_ns.clj

> Fixes https://github.com/clojure-emacs/cider-nrepl/issues/755
With these changes, responses are now enhanced with the following structural changes:
```diff
+{:elapsed-time {:humanized "Completed in 1028 ms", :ms 1028},
+ :ns-elapsed-time
+ {:failing-test-ns {:humanized "Completed in 1026 ms", :ms 1026}},
:summary {:error 0, :fail 2, :ns 1, :pass 0, :test 2, :var 2},
:testing-ns "failing-test-ns",
:gen-input [],
:status #{"done"},
:id "52816a02-86cc-457a-a9fa-b287e90da189",
:session #{"e3b12907-d64e-4e6d-902a-ab63fef9c811"},
:results
{:failing-test-ns
{:fast-failing-test
[{:index 0,
:ns "failing-test-ns",
:file "failing_test_ns.clj",
:type "fail",
:diffs [["1\n" ["0\n" "1\n"]]],
:line 5,
:var "fast-failing-test",
:expected "0\n",
:context [],
+    :elapsed-time {:humanized "Completed in …
```

`test`: provide timing information

---

CHANGELOG.md
src/cider/nrepl/middleware/track_state.clj

Part of https://github.com/clojure-emacs/cider/issues/3385
Cheers - V

`track-state`: Include `cljs.core` ns info

---

test/clj/cider/nrepl/middleware/slurp_test.clj

This deftest started failing, following clojure.org changes (now it returns 403 instead of 404, and with a different content-type).
I found it can't be fixed, because the test was giving false negatives to begin with. The `;; When a url gives content type as nil, then default content-type should be taken.` comment describes a behavior that isn't real.
To prove so one can try these changes instead https://github.com/clojure-emacs/cider-nrepl/commit/bd46a9c1642e4c7ea4e9684d533aad592a36a680 (that altered deftest can't pass).
I propose simply removing the test. After all, this should be a slowly changing area. New PRs can add coverage if they change stuff.
Cheers - V

Remove `test-url-content-type`

---

CHANGELOG.md
doc/modules/ROOT/pages/nrepl-api/ops.adoc
src/cider/nrepl.clj
src/cider/nrepl/middleware/ns.clj
test/clj/cider/nrepl/middleware/ns_test.clj
test/cljs/cider/nrepl/middleware/cljs_ns_test.clj

Previously, `ns-path` could return responses that were often of no use in clojurescript.
For instance, `"conduit/events.cljs"` cannot be open (lacks a src/test component) except if a matching Emacs buffer happened to be open already.
So this PR adds a `:url` attribute, as documented.
Works:
```
(-->
id         "35"
op         "ns-path"
session    "3c26ce70-2c20-4b3a-9d14-017c7497f663"
time-stamp "2023-08-27 15:57:14.251984000"
ns         "conduit.events"
)
(<--
id         "35"
session    "3c26ce70-2c20-4b3a-9d14-017c7497f663"
time-stamp "2023-08-27 15:57:14.253630000"
path       "conduit/events.cljs"
status     ("done")
url        "file:/Users/vemv/conduit/src/conduit/events.cljs"
)
```

`"ns-path"` op: also include a `:url` attribute in the response

---

CHANGELOG.md
Makefile
src/cider/nrepl/middleware/track_state.clj

I was perceiving  this stacktrace:
```
Exception updating the ns-cache #error {
:cause /Users/vemv/orchard/does-not-exist.jar
:via
[{:type java.util.concurrent.ExecutionException
:message java.nio.file.NoSuchFileException: /Users/vemv/orchard/does-not-exist.jar
:at [java.util.concurrent.FutureTask report FutureTask.java 122]}
{:type java.nio.file.NoSuchFileException
:message /Users/vemv/orchard/does-not-exist.jar
:at [sun.nio.fs.UnixException translateToIOException UnixException.java 92]}]
:trace
[[sun.nio.fs.UnixException translateToIOException UnixException.java 92]
[sun.nio.fs.UnixException rethrowAsIOException UnixException.java 106]
[sun.nio.fs.UnixException rethrowAsIOException UnixException.java 111]
[sun.nio.fs.UnixFileAttributeViews$Basic readAttributes …
```

`middleware.track-state`: handle non-existing .jar files that may be in the classpath

---

.circleci/config.yml
.clj-kondo/config.edn
CHANGELOG.md
Makefile
README.md
doc/modules/ROOT/pages/nrepl-api/ops.adoc
project.clj
src/cider/nrepl.clj
src/cider/nrepl/middleware/debug.clj
src/cider/nrepl/middleware/info.clj
test/clj/cider/nrepl/middleware/format_test.clj
test/clj/cider/nrepl/middleware/info_test.clj
test/smoketest/project.clj

Commits:
* Bump Orchard
* Modernize clj-kondo setup
* Use mranderson more cleanly
* Add enrich-classpath to the Makefile
* README: document Make tasks
* Adapt `format-test`
* `info` and `eldoc` ops: also return `:doc-fragments` when available
The last commit, of course, is the most important one. Fortunately it's very thin, as it simply forwards attributes from Orchard.
Cheers - V

`info` and `eldoc` ops: also return `:doc-fragments` when available

---

.gitignore
CHANGELOG.md
Makefile
doc/modules/ROOT/pages/nrepl-api/ops.adoc
project.clj
src/cider/nrepl.clj
src/cider/nrepl/middleware/info.clj
test/clj/cider/nrepl/middleware/info_test.clj

Fixes https://github.com/clojure-emacs/cider-nrepl/issues/812
Tested out locally - works as intended!
Cheers - V

`info` and `eldoc` ops: accept a Compliment-style `context` parameter

---

CHANGELOG.md
Makefile
README.md
doc/modules/ROOT/pages/usage.adoc
project.clj

*  Bump `orchard` to 1.5.1
* 0.38.1
https://github.com/clojure-emacs/orchard/blob/v0.15.1/CHANGELOG.md#0151-2023-09-21
https://clojars.org/cider/orchard/versions/0.15.1

Bump `orchard` to 1.5.1

---

CHANGELOG.md
src/cider/nrepl/middleware/info.clj
test/clj/cider/nrepl/middleware/info_test.clj

Documentation wasn't showing up for `..` when providing a context.

`info` and `eldoc` ops: fix regression for the special form `..`

---

.circleci/config.yml
.gitignore
Makefile
README.md
project.clj
test/clj/cider/nrepl/middleware/info_test.clj
test/clj/cider/nrepl/plugin_test.clj

* Exercise enrich-classpath in CI
* Exercise each of the three Orchard Java parsers
* This is accomplished by either of
* excluding enrich-classpath;
* including it partially (removing the `--add-opens` flags it adds);
* or including it fully.
It is valuable to check that our usual tests don't fail in presence of Enrich. Just a couple tests had to be adapted (for the better: with enrich in, the assertion is richer).
It's basically the same setup I introduced in https://github.com/clojure-emacs/orchard/pull/192 , with some variations.
Cheers - V

Exercise enrich-classpath and all Orchard Parser variants in CI

---

CHANGELOG.md
project.clj

I encountered the following locally:
Caused by: java.lang.ClassNotFoundException: cidernrepl0381.mx.cider.orchard.LruMap
which is caused by the .java file bundled by Orchard - mranderson is struggling to inline it.
I propose to un-inline this dep, just like we do for logjam, based on the following considerations:
* cider-nrepl, being its main consumer, will always pull _latest_
* (more recent versions are more likely to be chosen by dependency resolution algos)
* orchard is dependency-free.
* orchard tries hard not to inflict breaking changes.
We could eventually inline Orchard (and logjam) again some day, but I sense mranderson would need some attention first.
Cheers - V

Don't inline orchard anymore

---

CHANGELOG.md
Makefile
README.md
doc/modules/ROOT/pages/usage.adoc
src/cider/nrepl/middleware/out.clj
src/cider/nrepl/middleware/track_state.clj
test/clj/cider/nrepl/middleware/out_test.clj
test/clj/cider/nrepl/middleware/track_state_test.clj

* `track-state`: include var info for macros defined for ClojureScript namespaces.
* e.g. for `foo.cljs`, now var info for any macros contained in `foo.clj` is also included.
* 0.40.0

`track-state`: include var info for macros defined for ClojureScript namespaces

---

CHANGELOG.md
Makefile
README.md
doc/modules/ROOT/pages/nrepl-api/ops.adoc
doc/modules/ROOT/pages/usage.adoc
project.clj
src/cider/nrepl.clj
src/cider/nrepl/middleware/inspect.clj
test/clj/cider/nrepl/middleware/inspect_test.clj

> Part of https://github.com/clojure-emacs/cider/issues/3529

`middleware.inspect:` add new `inspect-previous-sibling`, `inspect-next-sibling` ops

---

.circleci/config.yml
CHANGELOG.md
README.md
src/cider/nrepl.clj

Fixes https://github.com/clojure-emacs/cider-nrepl/issues/828
I verified it works as intended, shaving 12s for the first time `*cider-error*` pops up.

Warmup Orchard caches for exceptions in advance

---

.gitattributes
CHANGELOG.md
doc/modules/ROOT/pages/nrepl-api/ops.adoc
maint/cider/nrepl/impl/docs.clj
src/cider/nrepl.clj
src/cider/nrepl/middleware/inspect.clj
src/cider/nrepl/middleware/stacktrace.clj
test/clj/cider/nrepl/middleware/stacktrace_test.clj

* Avoid problematic newline in docs
* See https://docs.cider.mx/cider-nrepl/nrepl-api/ops.html#info
* Introduce `inspect-last-stacktrace-exception` op
* Part of https://github.com/clojure-emacs/cider/issues/3565
* `lein docs`: Add missing `shutdown-agents` call
Cheers - V

Introduce `inspect-last-stacktrace-exception` op

---

CHANGELOG.md
doc/modules/ROOT/pages/nrepl-api/ops.adoc
project.clj
src/cider/nrepl.clj
src/cider/nrepl/middleware/inspect.clj
test/clj/cider/nrepl/middleware/inspect_test.clj

> Closes https://github.com/clojure-emacs/orchard/issues/207
I was on the fence about doing this in cider-nrepl (vs. in Orchard). Finally cider-nrepl seemed a better choice, so that `orchard.inspect` can keep doing one thing only.
In the end, the :doc-fragments stuff is dramatically different (schema-wise) from the Inspector `:value` stuff, so putting it all under the same map in Orchard might be confusing.
Cheers - V

Inspector: include `:doc-fragments` for all responses which `:value` is a Class, Field or Method

---

CHANGELOG.md
src/cider/nrepl.clj
src/cider/nrepl/middleware/inspect.clj
test/clj/cider/nrepl_test.clj

* middleware.inspect: optimize `future` usage
* Warmup the Orchard cache for project `:import`s
* Speculatively improves completion/info performance for the classes that users are more likely to use in a given project.

Warmup the Orchard cache for project `:import`s

---

.clj-kondo/config.edn
CHANGELOG.md
project.clj
src/cider/nrepl/middleware/inspect.clj
src/cider/nrepl/middleware/test.clj
test/clj/cider/nrepl/middleware/inspect_test.clj
test/clj/cider/nrepl/middleware/test_test.clj

It broke at some point, possibly long ago, as it was showing the same inspector instead of a refreshed one.
Cheers - V

Fix `"inspect-refresh"` op

---

doc/modules/ROOT/pages/usage.adoc

Use -M to avoid warnings
WARNING: Use of :main-opts with -A is deprecated. Use -M instead.
WARNING: Implicit use of clojure.main with options is deprecated, use -M
- [*] The commits are consistent with our [contribution guidelines](../blob/master/.github/CONTRIBUTING.md)
- [*] You've added tests to cover your change(s)
- [*] All tests are passing
- [*] You've updated the README
- [*] Middleware documentation is up to date
* Run `lein docs` afterwards, and commit the results.
"Design" section of the …

Update usage.adoc: Use clj -M to avoid warnings

---

.circleci/config.yml
doc/modules/ROOT/pages/compatibility.adoc
doc/modules/ROOT/pages/usage.adoc
project.clj
src/cider/nrepl/middleware/stacktrace.clj
src/cider_nrepl/plugin.clj
test/clj/cider/nrepl/middleware/inspect_test.clj
test/common/cider_nrepl/plugin_test.clj
test/smoketest/project.clj

> Closes https://github.com/clojure-emacs/cider-nrepl/issues/836
1.8 compat, while it was intended to be, was broken for a possibly very long time.
The reason being, the CI matrix as introduced in 1016f61754c5bcf58ed745a88620381f4afc749d was broken: CircleCI set `VERSION`, while the Makefile expected `CLOJURE_VERSION`.
So, surely, progressively factual support degraded.
This commits fixes 1.9 compatibility and ensures that the CI matrix runs as intended.
I deem 1.8 not worth fixing, given that:
* it was broken already;
* nobody complained;
* we planned to drop it; and most importantly
* it was hard to restore, since it would mean running an older Leiningen (Lein has used 1.9+ features for over 5 years, which means that the CCI images would have to be replaced with something else)
* In …

Restore 1.9 compat, drop 1.8 compat

---

.circleci/config.yml

Similar to https://github.com/nrepl/nrepl/pull/305
1. Replaced exclusions with more precise matrix sets. 
2. Removed clj 1.9 together with JDK higher than 8. The motivation for it is that Clojure 1.10 contains important fixes for compatibility with Java9+ (see https://github.com/clojure/clojure/blob/master/changes.md#11-java). Anyone who cares enough about using newer JDKs must eventually upgrade Clojure as well.

[ci] Refactor CI wrt JDK8 and Clojure 1.9 compatibility

---

CHANGELOG.md
project.clj

https://github.com/clojure-emacs/clj-suitable/blob/v0.6.2/CHANGELOG.md#062-2033-01-14

Bump `suitable` to 0.6.2

---

CHANGELOG.md
src/cider/nrepl/middleware/debug.clj

Fixes #846
* Run `lein docs` afterwards, and commit the results.
Thanks!
***
1. `resolve` have an extra arity for `&env`
2. I added arity for `looks-step-innable?` for backwards compatibility
```clojure
(defn ns-resolve
"Returns the var or Class to which a symbol will be resolved in the
namespace (unless found in the environment), else nil.  Note that
if the symbol is fully qualified, the var/Class to which it resolves
need not be present in the …
```

Fix the debugger in case of a local shadows a var

---

README.md
doc/modules/ROOT/pages/nrepl-api/ops.adoc
doc/modules/ROOT/pages/usage.adoc
project.clj
src/cider/nrepl.clj
src/cider/nrepl/middleware.clj
src/cider/nrepl/middleware/reload.clj
test/clj/cider/nrepl/middleware/reload_test.clj

Fix #849
* Run `lein docs` afterwards, and commit the results.
Thanks!

Support clj-reload workflow

---

CHANGELOG.md
doc/modules/ROOT/pages/nrepl-api/ops.adoc
src/cider/nrepl.clj
src/cider/nrepl/middleware/refresh.clj
src/cider/nrepl/middleware/reload.clj
src/cider/nrepl/middleware/util/reload.clj
test/clj/cider/nrepl/middleware/refresh_test.clj

Moves shared code to a new ns.

`cider.nrepl.middleware.reload`: support `:before` / `:after` functions

---

CHANGELOG.md
src/cider/nrepl.clj

Adapting it to the new `cider.nrepl.middleware.reload` ops.

Expand `ops-that-can-eval`

---

CHANGELOG.md
doc/modules/ROOT/pages/nrepl-api/ops.adoc
doc/modules/ROOT/pages/nrepl-api/supplied_middleware.adoc
project.clj
src/cider/nrepl.clj
src/cider/nrepl/middleware/debug.clj
src/cider/nrepl/middleware/inspect.clj
src/cider/nrepl/middleware/log.clj
test/clj/cider/nrepl/middleware/debug_test.clj
test/clj/cider/nrepl/middleware/inspect_test.clj
test/cljs/cider/nrepl/middleware/cljs_inspect_test.clj

Update Orchard to the latest version. This gets all latest inspector updates and new `orchard.print` namespace.

Use new Orchard

---

CHANGELOG.md
project.clj

Especially relevant for its new internal locking
(we had internal `locking` for `refresh` but not `reload`)

Use clj-reload 0.6.0

---

CHANGELOG.md
src/cider/nrepl/middleware/refresh.clj

> Closes https://github.com/clojure-emacs/cider/issues/3652

`middleware.refresh`: elide a lock for the `"refresh-clear"` op

---

CHANGELOG.md
project.clj

Since the last update:
- Fix fuzzy matching logic (`rema` didn't match re-matches).
- Optimize the way how cached values are looked up.
- Reduce the memory footprint of the cache.
- Deprecate `:plain-candidates` in `complliment.core/completions`.

Use Compliment 0.5.5

---

CHANGELOG.md
doc/modules/ROOT/pages/nrepl-api/ops.adoc
project.clj
src/cider/nrepl.clj
src/cider/nrepl/middleware/inspect.clj
test/clj/cider/nrepl/middleware/inspect_test.clj

Sister to clojure-emacs/orchard#269. This is how it would look like on the cider-nrepl side. Old ops are retained for compatibility and marked as deprecated.

[inspector] Use orchard.inspect/refresh instead of individual setters

---

CHANGELOG.md
doc/modules/ROOT/pages/nrepl-api/ops.adoc
src/cider/nrepl.clj
src/cider/nrepl/middleware/inspect.clj
test/clj/cider/nrepl/middleware/inspect_test.clj

1. Adding `:view-mode` as a supported config options passed from CIDER to Orchard. This part is straightforward.
2. Given that I wanted the view-mode to be a toggle, the best place for toggling logic is here. Adding it on CIDER side would require CIDER to know what is the current view-mode of the inspector which is extra work. cider-nrepl has that information though, so it's easy to do it here.

[inspect] Introduce support for :view-mode config and inspect-toggle-view-mode op

---

CHANGELOG.md
doc/modules/ROOT/pages/nrepl-api/ops.adoc
project.clj
src/cider/nrepl.clj
src/cider/nrepl/middleware/inspect.clj
test/clj/cider/nrepl/middleware/inspect_test.clj

After using the new view-mode functionality locally for some time, I concluded that in 99% of cases you only want to toggle `:object` view mode for the currently inspected value. When you subsequently click on one of the fields to inspect further, you'd rather see the normal view mode again. So, in my experience, it looked like `v`, click the field with usually a recognizable data structure, `v` again to toggle back to normal view mode.
I propose to make this behavior the default one. When the user navigates away from the current view, the view-mode will reset. For that, I've introduced a concept of "transient config values".
In this PR, any action other than `toggle-view-mode` will reset the view-mode back to `:normal`. Now that I think of it, some actions make sense to preserve the view …

[inspect] Use new stack-based view mode

---

CHANGELOG.md
Makefile
README.md
doc/antora.yml
doc/modules/ROOT/pages/about/history.adoc
doc/modules/ROOT/pages/compatibility.adoc
doc/modules/ROOT/pages/index.adoc
doc/modules/ROOT/pages/internals.adoc
doc/modules/ROOT/pages/usage.adoc

Notable changes:
- Removed mentions of Boot as part of the soft-deprecation process (@bbatsov).
- Trimmed the compatibility table to leave only versions where compatibilities have changed.
Ignore the 0.49.0 commit, I will rebase it when that PR is merged.

Cleanup the docs

---

CHANGELOG.md
src/cider/nrepl/middleware/track_state.clj
test/clj/cider/nrepl/middleware/track_state_test.clj

> Fixes https://github.com/clojure-emacs/cider/issues/3684

Don't apply indentation inference for `:style/indent nil` metadata

---

CHANGELOG.md
src/cider_nrepl/plugin.clj
test/clj/cider/nrepl/plugin_test.clj
test/common/cider_nrepl/plugin_test.clj

Turns out, it was a bad idea to set the minimal Clojure version to `1.10.3` - a patch version that was released much later than the original 1.10.0. Since we don't really care as long as it's 1.10, I propose to reduce the requirement.
Context: https://clojurians.slack.com/archives/C0617A8PQ/p1718210427715849

Decrease minimal Clojure version in Leiningen plugin to 1.10.0

---

CHANGELOG.md
project.clj
test/clj/cider/nrepl/middleware/complete_test.clj

This version brings new 1.12 completions for class members like `Thread/.interrupt` or `Thread/new`.

[complete] Bump Compliment to 0.6.0

---

Makefile
project.clj

Tools.cli is brought by cljfmt. In cljfmt, it's only used in `cljfmt.main` namespace to parse args in the main entrypoint. We don't touch that namespace in cider-nrepl, so it should be safe to drop this dependency.
https://github.com/search?q=repo%3Aweavejester%2Fcljfmt%20tools.cli&type=code

Exclude tools.cli from dependencies

---

.circleci/config.yml
CHANGELOG.md
Makefile
src/cider/nrepl.clj
src/cider/nrepl/middleware/inspect.clj
src/cider/nrepl/middleware/macroexpand.clj
src/cider/nrepl/middleware/util/error_handling.clj
test/clj/cider/nrepl/middleware/macroexpand_test.clj
tools-deps-testing/deps.edn
tools-deps-testing/example.clj
tools-deps-testing/macroexpand_tools_deps_test.clj

This PR is a quite significant do-over of macroexpansion middleware.
The current implementation of CLJ macroexpander performs the expansion in the "middleware context". Because of that, the middleware has to carefully recreate an eval-like context (bind `*ns*`, ensure `LOADER` is bound), and problems like #886 still fall through. But we already have the eval-like context set up in the interruptible-eval middleware. This approach is already used by the `inspect` middleware for the initial inspector start command – it is a flavor of `eval` message that is intercepted by inspect mw on its way out.
I propose to do the same for macroexpansion – let the `eval` mw perform the expansion with all the correct dynamic bindings and context, just like if the user typed `(macroexpand 'form)` at the …

[macroexpand] Make macroexpand mw delegate the expansion to eval

---

.circleci/config.yml
CHANGELOG.md
doc/modules/ROOT/pages/usage.adoc
project.clj
test/clj/cider/nrepl/middleware/info_test.clj

Removed "Boot testing" section from tests – this looks like some leftover because it doesn't seem to me like it tests anything Boot-specific (or touches Boot at all).
Removed boot jars from `:test` profile – looks like this was meant for Eastwood to check `cider.tasks`.
`cider.tasks` for adding cider-nrepl to `boot repl` task still remains.

Bump Orchard to 0.27.0

---

.circleci/config.yml
.clj-kondo/config.edn
CHANGELOG.md
Makefile
README.md
project.clj
src/cider/nrepl/middleware/test.clj
test/clj/cider/nrepl/middleware/info_test.clj
test/clj/cider/nrepl/middleware/inspect_test.clj
test/clj/cider/nrepl/middleware/test_test.clj
test/clj/cider/nrepl/plugin_test.clj
test/smoketest/src/smoketest/core.clj

This PR gives the same treatment to CI/testing as https://github.com/clojure-emacs/orchard/pull/288.
1. Pull in JDK sources which were missing so that Java parsing capabilities can be tested.
2. Test parsers on JDK21 where we have the sources.
3. Simplify testing setup, remove dependency on enrich-classpath for testing, remove the necessity for Cognitest.
4. Move `smoketest` runs back into every `test` job since it already has sources MrAndersoned. Just don't clean them beforehand, so the smoketest is fast then.
---

Redo testing

---

CHANGELOG.md
doc/modules/ROOT/pages/nrepl-api/ops.adoc
src/cider/nrepl.clj

Hi,
could you please review patch to do limited upated to the `info` op documentation. It partially addresses #885, specifically https://github.com/clojure-emacs/cider-nrepl/issues/885#issuecomment-2356676689.
There are no functional changes. This update provides a reference for the basic usage of `info`, particularly clarifying that the `file` return key value should be either a URI or a relative path.
The new descriptions were determined empirically by examining log messages in CIDER. I'm open to corrections.
(Note: An unexpected `expander` entry appeared in the generated ops doc, which seems to have been missed in #894.)
Thanks …

Limited doc update for info op

---

project.clj

I'm not sure if this deserves a changelog mention. After all, I don't think it is "correct" to include just cider-nrepl and assume it pulls a correct nrepl version.

Bump nREPL and Piggieback versions

---

project.clj
src/cider/nrepl.clj
src/cider/nrepl/middleware/info.clj
src/cider/nrepl/middleware/track_state.clj
src/cider/nrepl/middleware/util/meta.clj
src/cider/nrepl/middleware/xref.clj

Sister PRs: https://github.com/clojure-emacs/orchard/pull/310, https://github.com/clojure-emacs/cider/pull/3769.
Not a lot of changes were needed here. Given how things are implemented on the Orchard side, cider-nrepl only needs to set up a correct `*download-sources-jar-fn*` before calling out to Orchard functions that do Java sources discovery.
We maintain a ConcurrentHashMap (logically, a set, but there is no ConcurrentHashSet, and CHM API for this usecase is cleaner than `(atom #{})`) of Maven coordinates (`groupId/artifactId "version"`) of the dependencies we already tried downloading sources once. If it succeeded, we won't call this function again anyway, if it failed, the CHM will prevent trying for the second time. This debouncer only exists in memory which I suppose makes it …

[info] Add support for automatically downloading sources JARs

---

CHANGELOG.md
doc/modules/ROOT/pages/nrepl-api/ops.adoc
src/cider/nrepl.clj
src/cider/nrepl/middleware/inspect.clj
test/clj/cider/nrepl/middleware/info_test.clj
test/clj/cider/nrepl/middleware/inspect_test.clj

I propose to remove the feature that displays parsed Javadoc in the inspector buffer when inspecting classes, methods, and fields. It currently looks like this:
While the idea of uniting the inspector, doc browser, and stacktrace viewer in a coherent UX is a sound one, the current implementation is not ideal. 
- The javadoc is shown at the very bottom of the inspector and usually takes a lot of scrolling to reach. 
- The free-form text looks quite out of place in the inspector buffer.
- Compared to a `*cider-doc*` buffer, the inspector view lacks jump-to-definiton and online Javadoc buttons.
- This implementation complicates the inspector on both Clojure and Emacs sides.
I have a vision of tying `cider-doc` and the Inspector together through clickable buttons instead. This will be less …

[inspector] Don't show javadocs when inspecting classes

---

CHANGELOG.md
doc/modules/ROOT/pages/nrepl-api/ops.adoc
project.clj
src/cider/nrepl.clj
src/cider/nrepl/middleware/debug.clj
src/cider/nrepl/middleware/log.clj
src/cider/nrepl/middleware/reload.clj
src/cider/nrepl/middleware/stacktrace.clj
src/cider/nrepl/middleware/test.clj
src/cider/nrepl/middleware/util/error_handling.clj
src/cider/nrepl/middleware/util/reload.clj
test/clj/cider/nrepl/middleware/info_test.clj
test/clj/cider/nrepl/middleware/log_test.clj
test/clj/cider/nrepl/middleware/stacktrace_test.clj
test/clj/cider/nrepl/middleware/test_test.clj

Multiple things going on in this PR:
1. Remove analyze-stacktrace ops (the ones that took an exception printed as string, parsed it, and returned as an exception object that can be presented via `*cider-error*`). The idea is that https://github.com/clojure-emacs/orchard/pull/320 will cover the usecases where user wants to jump to source location from a printed stacktrace, and that is more discoverable than a separate quite obscure command.
2. Replace the usage of `haystack.analyzer` with `orchard.stacktrace`. The latter is almost the same as the former, but with improvements and optimizations. See https://github.com/clojure-emacs/orchard/pull/322.
3. I rewrote a few test namespaces along the way to use matcher-combinators to reduce noise and improve error reporting.
I plan to let it hang …

Haystack to Orchard

---

src/cider/nrepl/middleware/debug.clj
src/cider/nrepl/middleware/info.clj
src/cider/nrepl/middleware/log.clj
src/cider/nrepl/middleware/macroexpand.clj
src/cider/nrepl/middleware/profile.clj
src/cider/nrepl/middleware/refresh.clj
src/cider/nrepl/middleware/reload.clj
src/cider/nrepl/middleware/slurp.clj
src/cider/nrepl/middleware/stacktrace.clj
src/cider/nrepl/middleware/test.clj
src/cider/nrepl/middleware/util.clj
src/cider/nrepl/middleware/util/reload.clj
src/cider/nrepl/middleware/version.clj

There is a very common pattern used everywhere in cider-nrepl:
```clj
(transport/send (:transport msg) (response-for msg ...))
```
This PR commemorates this pattern as a function `respond-to` and replaces all matching usages with it. Perhaps, this is something that could live in nREPL itself, but we'll still have to support older versions of nREPL here, so might as well add it here.

[util] Add util/respond-to

---

CHANGELOG.md
project.clj
src/cider/nrepl/middleware/debug.clj
src/cider/nrepl/middleware/reload.clj
src/cider/nrepl/middleware/stacktrace.clj
src/cider/nrepl/middleware/test.clj
src/cider/nrepl/middleware/util/error_handling.clj
src/cider/nrepl/middleware/util/reload.clj

Bump Orchard to 0.31.1

---

CHANGELOG.md
doc/modules/ROOT/pages/nrepl-api/ops.adoc
src/cider/nrepl.clj
src/cider/nrepl/middleware/complete.clj
test/clj/cider/nrepl/middleware/complete_test.clj

So, I've merged the new Compliment that brought this: https://github.com/alexander-yakushev/compliment/pull/122. The idea is to improve the order of candidates with information from the backend.
However, I couldn't make it work right away. Turns out, company-mode (and Emacs' own complete-at-point) perform their own client-side post-sorting of candidates – which they do by-name). To get rid of it, there is a metadata parameter that can be assigned to completion backend to avoid client-side sorting. I did that, so now the backend results come as is. And they come in like this, for example:
Notice the weird order – a `java.` class first, then two `javax.` classes, then a `java.` class again. It is because Compliment's own default sorting method is `:by-length` – shorter candidates first. …

[complete] Make sort-order customizable

---

CHANGELOG.md
src/cider/nrepl/middleware/test.clj
test/clj/cider/nrepl/middleware/test_test.clj

Fixes #916 
This PR performs a clojure.walk to covert all maps to sorted-maps when printing an object in the test results. See #916 for example before and after screenshots of the diffed data.
---
* Run `lein docs` afterwards, and commit the results.
Thanks!

Sort printed maps in test output

---

CHANGELOG.md
project.clj
src/cider/nrepl/pprint.clj

So, here's another attempt to reduce the surface of cider-nrepl dependency. The proposal is based on this completely unscientific test that checks how many people are using non-standard pretty-printers with CIDER. Out of 15 responses, 2 are using Fipp and 1 is using Puget.
The idea in the PR is to revert to clojure.pprint if Puget could not be loaded. We also print a warning to tell the user what's going on. I'd say this is graceful UX degradation as the results are still being pretty-printed, and there is a path for the user to fix this. One flow I'm worried about is the `cider-jack-in` one where user haven't ever set up a custom profile to put extra dependencies there.
There's no rush with this one, I'll be happy to know what you think.
---

Stop shipping Puget with cider-nrepl

---

src/cider/nrepl/middleware/test.clj
test/clj/cider/nrepl/middleware/test_test.clj

#917 introduced a small bug where matcher-combinators results that contain records are converted to maps, and then the way they are printed gets broken.
---

[test] Don't turn records into maps when post-processing test results

---

CHANGELOG.md
doc/modules/ROOT/pages/nrepl-api/ops.adoc
src/cider/nrepl.clj
src/cider/nrepl/middleware/inspect.clj
test/clj/cider/nrepl/middleware/inspect_test.clj

Sister PR: https://github.com/clojure-emacs/orchard/pull/331
Not a lot to be done here. We already have `inspector-toggle-view-mode` that does the heavy lifting. The only meaningful thing here is checking if the current object can be rendered as a table.
- If it does, the view mode cycle goes like `normal -> table -> object -> normal`
- Otherwise, it's `normal -> object -> normal`.
---

[inspect] Add support for :table view-mode

---

CHANGELOG.md
doc/modules/ROOT/pages/nrepl-api/ops.adoc
doc/modules/ROOT/pages/nrepl-api/supplied_middleware.adoc
project.clj
src/cider/nrepl.clj
src/cider/nrepl/middleware.clj
src/cider/nrepl/middleware/inspect.clj
src/cider/nrepl/middleware/profile.clj
src/cider/nrepl/middleware/track_state.clj
src/cider/nrepl/middleware/util/meta.clj
test/clj/cider/nrepl/middleware/profile_test.clj

Sister PR: https://github.com/clojure-emacs/orchard/pull/333
- Bumped Orchard
- Removed thunknyc/profile from dependencies
- Dropped several ops from the middleware – things like individual function summaries, tuning max sample count, stuff like that. Only four ops remain: toggle profile for a var, for a whole ns, clear results, and render results via the inspector.
- Renamed the remaining ops to have `cider/` prefix. I briefly tried keeping the semblance of backward compatibility and keep old names too, but since the most important op (summary) is not compatible with its old implementation, it provides no value. GIven that the feature is an obscure one, I don't care much about breakages here.
- Added `:orchard.profile/profiled` as a relevant meta key – we can then outline vars with it in …

[profile] Migrate profiling middleware to orchard.profile

---

CHANGELOG.md
doc/modules/ROOT/pages/nrepl-api/ops.adoc
src/cider/nrepl.clj
src/cider/nrepl/middleware/stacktrace.clj

Changes made to address https://github.com/clojure-emacs/cider/issues/3804.
1. The op `inspect-last-exception` now accepts `ex-data: true` parameter that tells it the user wants to inspect ex-data of the exception directly, not the entire exception. This is used to have separate buttons in `*cider-error*` buffer for the whole exception and for just ex-data.
2. Replaced a separate dynamic variable manually stored in the session with storing the last analyzed exception inside session's metadata – the same approach as used by inspector middleware.
---

[stacktrace] Add support for directly inspecting ex-data

---

src/cider/nrepl/middleware/track_state.clj
test/clj/cider/nrepl/middleware/track_state_test.clj

I can't believe it took me this long to get to this. The current implementation of `track-state` is very far from ideal and I had problems with it for a long time (see #806). In the current large project I'm testing this, every eval op takes ~300-400ms to recalculate the updated state (even if there were no changes to relevant metadata) and this produces ~250-300 MB of garbage. The state recalculation doesn't delay the evaluation result (as the state update happens on a separate thread), but it delays font lock updates which can be annoying. Besides, the allocated garbage produces extra strain if a REPL process is already low on memory. Finally, the cache used by this middleware occupies again ~200 MB of heap, and there is a counterpart cache on the Emacs side which eats memory and causes …

[track-state] Completely redesign track-state middleware

---

src/cider/nrepl/middleware/test.clj

CIDER includes generated input in reports when the generated input is made available, which happens when using `test.chuck` and its `checking` block.  Currently, generated input is made available only to the first test condition within a `checking` block.  Unfortunately, this means that the generated input is not reported anywhere in CIDER unless the first test condition fails.  As a result, the generated input is (in my experience) typically not reported in CIDER.
This PR addresses that issue by modifying the `cider.nrepl.middleware.test/current-report` atom selectively based on whether a `test.chuck` testing context is available, which results in the presence of a non-`nil` value in the `:gen-input` key of the report precisely when the report corresponds to an error generated in a …

Include generated input with each test.chuck `checking` block error

---

CHANGELOG.md
doc/modules/ROOT/pages/nrepl-api/ops.adoc
project.clj
src/cider/nrepl.clj
src/cider/nrepl/middleware/inspect.clj
test/clj/cider/nrepl/middleware/inspect_test.clj

Hello,
this PR adds a new pretty view mode that uses the pretty printer from https://github.com/eerohele/pp via this PR in orchard https://github.com/clojure-emacs/orchard/pull/335. I believe there are no changes needed on the Emacs side.
TODO:
- Tests are failing because I need a new orchard version on ci, but how?
Open questions:
- Where should we put the pretty mode in the toggle list? I would put it after normal mode, 2nd position. Right now it is last, hard to reach In my opinion.
- When drilling down the inspector always switches to normal mode. If I'm in pretty mode I would like to stay there, and I would argue for other modes as well, if possible. right now you have to toggle a ton, to get that behaviour. 
Wdyt?
---
Before submitting a PR make sure the following things have been …

Add support for pretty printing values in the inspector.

---

CHANGELOG.md
project.clj
src/cider/nrepl/print_method.clj
test/clj/cider/nrepl/middleware/inspect_test.clj
test/clj/cider/nrepl/print_method_test.clj

Now that orchard.print has more printers for different classes, we can use it instead of custom code in cider-nrepl to modify `print-method` behavior. Brings more consistency and removes some code too.
One controversial change: different derefables like atoms, futures, etc., have changed how they look:
```clj
;; before
#atom[{:status :ready, :val 1} 0x11381415]
#promise[{:status :pending, :val nil} 0x2a40ec4d]
#delay[{:status :failed, :val #error {....}]
;; now
#atom[1]
#promise[<pending>]
#delay[<failed> #error[...]]
```
I hope this doesn't break anything – if people rely on printed representation of these objects, specifically on how cider-nrepl augments them, and then parse that, they are probably in a bigger trouble already.
---

Unify injected print-method implementations with orchard.print

---

CHANGELOG.md
doc/modules/ROOT/pages/nrepl-api/ops.adoc
src/cider/nrepl.clj
src/cider/nrepl/middleware/inspect.clj
test/clj/cider/nrepl/middleware/inspect_test.clj

This PR adds the `inspect-print-current-value` op. It prints the current value of the inspector with the user provided `::print/print-fn` or a default one.
It is used by CIDER in the `cider-inspector-print-current-value` command, bound to "P" in the inspector, to print it's current value. https://github.com/clojure-emacs/cider/pull/3810

Add inspect-print-current-value op

---

CHANGELOG.md
src/cider/nrepl/middleware/track_state.clj

Addresses #936.
See https://dowbecki.com/WeakHashMap-is-not-thread-safe/.
---

[track-state] Synchronize access to WeakHashMap cache

---

CHANGELOG.md
project.clj
src/cider/nrepl/pprint.clj

In the same way as Puget and zprint.
Additionally, default all three to `orchard.pp`, our new pretty-printing implementation that is faster than `clojure.pprint` and is also more consistent with the way we do printing in other parts of CIDER (inspector, debugger).
---

Stop shipping fipp with cider-nrepl

---

CHANGELOG.md
project.clj
src/cider/nrepl/middleware/DebugSupport.java
src/cider/nrepl/middleware/debug.clj
src/cider/nrepl/middleware/enlighten.clj
test/clj/cider/nrepl/middleware/debug_test.clj

We care about instrumentation size because when instrumenting large functions, we run into the JVM method size limit (65KB). This PR adds two improvements:
- Inject `DebugSupport/doBreak` instead of `c.n.m.debug/break`. Invoking a method requires less bytecode than calling a function. A method also has overrides for common primitives.
- Generate a more compact code for constructing a locals map.
---

[debug] Reduce instrumentation footprint 

---

CHANGELOG.md
project.clj
src/cider/nrepl/middleware/inspect.clj
test/clj/cider/nrepl/middleware/inspect_test.clj
test/cljs/cider/nrepl/middleware/cljs_inspect_test.clj

Bump Orchard to 0.35.0
