test/cider/nrepl/middleware/classpath_test.clj
test/cider/nrepl/middleware/format_test.clj
test/cider/nrepl/middleware/macroexpand_test.clj
test/cider/nrepl/middleware/resource_test.clj
test/cider/nrepl/middleware/trace_test.clj

As per Eastwood warnings and the style guide :-).

Prefer :require and :refer :all to :use

---

test/cider/nrepl/middleware/undef_test.clj

This makes the original test not fail on repeated invocations when using [lein-test-refresh](https://github.com/jakemcc/lein-test-refresh) and adds a few other cases.

Make undef test idempotent and add extra test cases

---

src/cider/nrepl/middleware/stacktrace.clj
test/cider/nrepl/middleware/stacktrace_test.clj

Fixes clojure-emacs/cider#1004.

Filter :repl-env key from exception data

---

src/cider/nrepl/middleware/ns.clj
test/cider/nrepl/middleware/ns_test.clj

Rename `value` slot in `ns-list` and `ns-vars` responses

---

src/cider/nrepl/middleware/util/instrument.clj

Invite user to file bug report when instrumenting fails

---

src/cider/nrepl/middleware/ns.clj
test/clj/cider/nrepl/middleware/ns_test.clj

Goes with https://github.com/clojure-emacs/cider/pull/1174

Add ns-list-vars-by-name op for listing all vars with a given name

---

src/cider/nrepl/middleware/debug.clj

Fix #bp to #break

---

src/cider/nrepl/middleware/debug.clj

This PR (along with the [cider side](https://github.com/clojure-emacs/cider/pull/1183)) does two things:
1. A new op to list all currently instrumented definitions. This is pretty reliable as far as `def`s go, but it doesn't do protocols. The cider side uses this to offer a `cider-browse-instrumented-defs` command.
2. A system for notifying cider whenever a new def has been instrumented or uninstrumented. So that cider can use that information to highlight instrumented defs in the source. [This video](https://twitter.com/AMalabarba/status/616192459933130752) shows that in action (the box around the name).
Item 1. is pretty straightforward, but I'd like some input on item 2.  
What it needs to do is wait for the `eval` op to finish, and then send a message to the client listing all the …

List instrumented defs

---

src/cider/nrepl/middleware/debug.clj
test/clj/cider/nrepl/middleware/debug_test.clj

Unrelated to that cider PR I posted just now.

Fix debugger inspect

---

eastwood.clj
project.clj
src/cider/nrepl/middleware/inspect.clj
src/cider/nrepl/middleware/util/inspect.clj
test/clj/cider/nrepl/middleware/inspect_test.clj

Let's get this train going. Previous discussion is at #123. This pull request handles the behind-the-scenes part of the feature.
Sister pull request is clojure-emacs/cider#1212.

Add pagination of long collections to inspector

---

project.clj
src/cider/nrepl/middleware/refresh.clj
src/cider/nrepl/version.clj
test/clj/cider/nrepl/middleware/info_test.clj

Here's my first cut at a conservative set of fixes on master since v0.10.0 was released. Let me know if I missed any that should be pulled in or pulled in anything that should be omitted.

Backported fixes for a 0.10.1 release

---

test/clj/cider/nrepl/middleware/apropos_test.clj

Gets 100% coverage of apropos. Also checks error handling.

Improve apropos's coverage tests

---

test/clj/cider/nrepl/middleware/complete_test.clj
test/cljs/cider/nrepl/middleware/cljs_complete_test.clj

-[x]The commits are consistent with our [contribution guidelines](CONTRIBUTING.md)
-[x]You've added tests to cover your change(s)
-[x]All tests are passing
-[x]The new code is not generating reflection warnings
-[n/a]You've updated the readme (if adding/changing middleware)
Thanks!
Added tests to exercise the complete middleware's error handling and
bring coverage to 100%

Improve complete middleware coverage tests

---

project.clj
test/clj/cider/nrepl/middleware/info_test.clj
test/java/cider/nrepl/test/AnotherTestClass.java
test/java/cider/nrepl/test/TestClass.java
test/java/cider/nrepl/test/YetAnotherTest.java

- [n/a] You've updated the readme (if adding/changing middleware)
Thanks!
Added tests to exercise the Javadoc URL issue [Fix #308].
Added test to see if the *remote-javadocs* functionality works (same fix as
above).
Changed some of the testing targets to internal test classes/methods
instead of testing against code outside of our control (when possible). As
a result, added a java source tree under the test directory and added
this to the test-clj profile.
Brings coverage back up to 100%.

Expand Info middleware tests

---

src/cider/nrepl/middleware/ns.clj
src/cider/nrepl/middleware/util/namespace.clj
test/clj/cider/nrepl/middleware/ns_test.clj
test/common/cider/test_ns/first_test_ns.clj
test/common/cider/test_ns/second_test_ns.clj
test/common/cider/test_ns/third_test_ns.clj

Add error checking to ns middleware and add tests

---

project.clj
test/clj/cider/nrepl/middleware/resource_test.clj

Thanks!
Resource-test wasn't actually pulling the "text.txt" file from the
test/resources directory since this directory was never added to the
resource-path list. Also added a test for the `resources-list` op.

Fix resource-test

---

src/cider/nrepl/middleware/ns.clj
src/cider/nrepl/middleware/track_state.clj
src/cider/nrepl/middleware/util/meta.clj
src/cider/nrepl/middleware/util/misc.clj
test/clj/cider/nrepl/middleware/ns_test.clj
test/clj/cider/nrepl/middleware/track_state_test.clj
test/clj/cider/nrepl/middleware/util/meta_test.clj
test/clj/cider/nrepl/middleware/util/misc_test.clj
test/cljs/cider/nrepl/middleware/cljs_ns_test.clj

Add a ns-vars-with-meta op to the ns middleware

---

src/cider/nrepl/middleware/info.clj
test/clj/cider/nrepl/middleware/info_test.clj

Thanks!
For clojure-emacs/cider#1725

Return class name as ns for Java interop methods

---

src/cider/nrepl/middleware/info.clj
test/clj/cider/nrepl/middleware/info_test.clj

Return Java interop method name in eldoc op

---

src/cider/nrepl/middleware/info.clj

Fixes #355
Fixes #354
Unfortunately due to the nature of jar resources, slurping it and then reading the string seems to be the best we can do. So since the original code was wrong and this at least works, I chose this tactic.
Rush please <3

Read see-also data in a jar safe fashion

---

src/cider/nrepl/middleware/info.clj
test/clj/cider/nrepl/middleware/info_test.clj
test/common/cider/test_ns/first_test_ns.clj

Support variables in eldoc op

---

src/cider/nrepl/middleware/refresh.clj
test/clj/cider/nrepl/middleware/refresh_test.clj

Thanks!
Not sure how to run all tests actually. I was able to run the clj ones with `lein with-profile +test-clj test` but i'm not sure if there's an easy way to run them all.
I'm also not sure how to ensure that I am not generating any reflection warnings but I don't think that I've added anything that would, but I'm happy to check this before merging.

Allow after fn's that can be called with no args

---

src/cider/nrepl/middleware/test.clj

Thanks!
test.check now reports minimal failing inputs (https://github.com/clojure/test.check/commit/73b12bcf18bfe1225511945332d331eda2ca104c).

[clojure-emacs/cider#1825] Adapt to latest test.check

---

src/cider/nrepl/middleware/refresh.clj
test/clj/cider/nrepl/middleware/refresh_test.clj

Thanks!
This sends information back to fix [the issue of refresh functions not resolved](https://github.com/clojure-emacs/cider/issues/1613)

Handle when functions not resolved in refresh

---

README.md

Update README for cider.tasks/add-middleware

---

project.clj

Fixes #385
I've also tested this locally following the reproduction steps in #385. I don't believe the remaining checkboxes apply to this PR, please correct me if I'm wrong.

Upgrade to tools.namespace:0.3.0-alpha3

---

project.clj

[Fix clojure-emacs/cider#1972] Bump the compliment dep to 0.3.4

---

src/cider/nrepl/middleware/test.clj
test/clj/cider/nrepl/middleware/test_test.clj

Addresses clojure-emacs/cider#1940
- [x ] All tests are passing
- [x ] The new code is not generating reflection warnings
Thanks!

Check test namespaces exist

---

src/cider/nrepl/middleware/pprint.clj

fipp and puget aren't used by default but together appear to take
over half a second to load. This change just delays loading of
the printers until use.
This makes some progress toward dealing with clojure-emacs/cider#1717 and is completely contained. I've got some other changes to help with the slow nrepl middleware namespaces, but those will come in another PR.

wait until a printer is used before requiring it.

---

src/cider/nrepl/middleware/util/meta.clj
test/clj/cider/nrepl/middleware/info_test.clj

Fix some name/ns issues with `resolve-special`

---

src/cider/nrepl/middleware/spec.clj
test/clj/cider/nrepl/middleware/spec_test.clj

See discussion in https://github.com/clojure-emacs/cider/issues/2030

Spec middleware, use re-find instead of re-matches to filter specs in spec-list

---

src/cider/nrepl/middleware/util/nrepl.clj

Accompany clojure-emacs/cider#2001.

Rename send-user-message to notify-client

---

.travis.yml
project.clj

to fix leiningen 2.8.x incompatibility issues

[Fix #449] Bump mranderson version

---

test/clj/cider/nrepl/middleware/debug_integration_test.clj
test/common/cider/nrepl/test/server.clj
test/common/cider/nrepl/test_session.clj

Add start-server wrapper to fix NREPL-87 in CI

Use ipv4 when ipv6 fails

---

project.clj
src/cider/nrepl/middleware/info.clj
src/cider/nrepl/middleware/resource.clj
src/cider/nrepl/middleware/stacktrace.clj
src/cider/nrepl/middleware/util/classloader.clj
src/cider/nrepl/middleware/util/namespace.clj
test/clj/cider/nrepl/middleware/classpath_test.clj
test/clj/cider/nrepl/middleware/debug_integration_test.clj
test/clj/cider/nrepl/middleware/info_test.clj
test/clj/cider/nrepl/middleware/resource_test.clj
test/common/cider_nrepl/plugin_test.clj
test/spec/cider/nrepl/middleware/info_test.clj

---
Please note that this is a breaking change to the resources list op. It now returns a dictionary, this will allow for more extension in the future if needed.

Fix boot-related classpath bugs & list resources

---

project.clj
test/clj/cider/nrepl/middleware/debug_integration_test.clj
test/src/cider/nrepl/middleware/debug_integration_test/fn.clj

Use dedicated file / function for debugging test

---

src/cider/nrepl/middleware/spec.clj
test/clj/cider/nrepl/middleware/spec_test.clj

Fixes https://github.com/clojure-emacs/cider-nrepl/issues/470

Add normalize-spec-form to normalize fn* into fn inside spec-form

---

src/cider/nrepl/middleware/info.clj

Thanks!
Nice catch @bbatsov! It would prevent some odd `Symbol not resolved` errors from being displayed.

Only include bound vars in see-also response

---

project.clj
src/cider/nrepl/middleware/classpath.clj
src/cider/nrepl/middleware/resource.clj
test/clj/cider/nrepl/middleware/classpath_test.clj

Fix #481.
Follow-up to #486.
**Note**: requires clojure-emacs/orchard#6 and artifact subsequent thereof.

Use `orchard.classpath`

---

README.md

Code coverage badge: replace coveralls.io with codecov.io

---

project.clj
src/cider/nrepl.clj
src/cider/nrepl/middleware/debug.clj
src/cider/nrepl/middleware/info.clj
src/cider/nrepl/middleware/out.clj
src/cider/nrepl/middleware/spec.clj
src/cider/nrepl/middleware/stacktrace.clj
src/cider/nrepl/middleware/test.clj
src/cider/nrepl/middleware/test/extensions.clj
src/cider/nrepl/middleware/util/error_handling.clj
src/cider/nrepl/middleware/util/instrument.clj
src/cider_nrepl/plugin.clj
test/clj/cider/nrepl/middleware/debug_integration_test.clj
test/clj/cider/nrepl/middleware/debug_test.clj
test/clj/cider/nrepl/middleware/info_test.clj
test/clj/cider/nrepl/middleware/spec_test.clj
test/clj/cider/nrepl/middleware/stacktrace_test.clj
test/clj/cider/nrepl/middleware/track_state_test.clj
test/common/cider/nrepl/test/server.clj
test/spec/cider/nrepl/middleware/info_test.clj
test/spec/cider/nrepl/middleware/stacktrace_spec_test.clj

This is the result of using `cljfmt fix` to adjust formatting that it doesn't agree with.
----
Thanks!

formatting tweaks to satisfy cljfmt in CI

---

README.md
project.clj
src/cider/nrepl.clj
src/cider/nrepl/middleware/profile.clj
test/clj/cider/nrepl/middleware/profile_test.clj

This is my attempt to solve https://github.com/clojure-emacs/cider/issues/1993#issuecomment-354975815
I am still having problems displaying the information on cider. I will need some guidance. 
- [x ] All tests are passing
- [x ] You've updated the readme (if adding/changing middleware)
Thanks!

#1993 integrating thunknyc profile to cider.

---

.travis.yml
Makefile
eastwood.clj
src/cider/nrepl.clj
src/cider/nrepl/middleware/ns.clj
src/cider/nrepl/middleware/profile.clj
src/cider/nrepl/middleware/refresh.clj
src/cider/nrepl/middleware/track_state.clj
src/cider/nrepl/middleware/util/instrument.clj
src/cider/nrepl/middleware/util/meta.clj
test/clj/cider/nrepl/middleware/info_test.clj
test/clj/cider/nrepl/middleware/profile_test.clj
test/clj/cider/nrepl/middleware/refresh_test.clj
test/clj/cider/nrepl/middleware/track_state_test.clj
test/clj/cider/nrepl/middleware/util/instrument_test.clj
test/clj/cider/nrepl/middleware/util/meta_test.clj
test/cljs/cider/nrepl/middleware/cljs_inspect_test.clj
test/spec/cider/nrepl/middleware/info_spec_test.clj

See discussion in #489 for an explanation what was done.
Kind of a lot going on here, but I made sure each "logical unit" of work is a distinct commit so you can view each piece separately.
-----
Thanks!

Fix #489 - reinstate mranderson on tests

---

src/cider/nrepl/middleware/test.clj
test/clj/cider/nrepl/middleware/test_filter_tests.clj
test/clj/cider/nrepl/middleware/test_test.clj

Extend selectors to include/exclude lists

---

src/cider/nrepl/middleware/util/coerce.clj

This works around the fact that cider.el sends `[]` for `false` in the case of
tests.  To do this, it runs `seq` against lists.  This is potentially
problematic for cases where you want to search no namespaces or vars, but these
circumstances seem far less common.
It also fixes a long-standing hidden bug where the `load?` variable was always
interpreted as `true`, due to it being `[]`.
Finally, it fixes the fact that `find-ns` was used in place of `find-var` in
the coercion.

Extend coercion to match cider's send format

---

project.clj

Bump the orchard dep to non-SNAPSHOT

---

project.clj
src/cider/nrepl/middleware/stacktrace.clj
test/clj/cider/nrepl/middleware/stacktrace_test.clj

This is IMO the simplest fix that can possibly work. Please let me know if there are ways to improve upon this.

[Fix #549] Fix spec error messages for Clojure 1.10

---

src/cider/nrepl/middleware/out.clj

Disabling auto flusher of `*out*` stream and adding a timer with 100ms flush intervals. Simplifying the `print-stream` function and fixing reflection warnings in this file on this occasion.

[Fix #561] Don't auto-flush out printer

---

project.clj

- change meta tag to `inline-dep`
- add alias for easily run lein tasks manually with the mranderson profile

Upgrade mranderson to 0.5.1

---

CHANGELOG.md
README.md
src/cider/tasks.clj

Not necessary anymore, see also https://github.com/clojure-emacs/cider/pull/2643.

Drop the cider.tasks/nrepl-server task

---

src/cider/nrepl/middleware/resource.clj

The boot hack found in the resource middleware is actually necessary down into
orchard.info/file-info for resource resolution.

Move boot-classloader hack from resource of to orchard

---

project.clj

- fixes #635
- fixes a calva issue (no context in completion msg)
- adds support for shadow-cljs
Thanks!

bump suitable dep to deal with no cljs environments

---

project.clj

Sorry, I introduced a bug in the fix yesterday.
Thanks!

bump suitable

---

project.clj

bump suitable: fixing nullpointer issue + friendlier error reporting

---

CHANGELOG.md

Just fixed a link as a markdown format :)

Fix a link in changelog

---

CHANGELOG.md
doc/modules/ROOT/pages/nrepl-api/ops.adoc
project.clj
src/cider/nrepl.clj
src/cider/nrepl/middleware/clojuredocs.clj
test/clj/cider/nrepl/middleware/clojuredocs_test.clj

Update to follow https://github.com/clojure-emacs/orchard/pull/96
I'll update project.clj when orchard's release is cut.

Use bundled ClojureDocs documents

---

project.clj

Bump mranderson

---

.circleci/config.yml
.clj-kondo/config.edn
.gitignore
Makefile
src/cider/nrepl/middleware/classpath.clj
src/cider/nrepl/middleware/complete.clj
src/cider/nrepl/middleware/content_type.clj
src/cider/nrepl/middleware/debug.clj
src/cider/nrepl/middleware/enlighten.clj
src/cider/nrepl/middleware/format.clj
src/cider/nrepl/middleware/info.clj
src/cider/nrepl/middleware/inspect.clj
src/cider/nrepl/middleware/macroexpand.clj
src/cider/nrepl/middleware/ns.clj
src/cider/nrepl/middleware/profile.clj
src/cider/nrepl/middleware/refresh.clj
src/cider/nrepl/middleware/slurp.clj
src/cider/nrepl/middleware/stacktrace.clj
src/cider/nrepl/middleware/test.clj
src/cider/nrepl/middleware/track_state.clj
src/cider/nrepl/middleware/util.clj
src/cider/nrepl/middleware/util/instrument.clj
src/cider/nrepl/middleware/xref.clj
src/cider/nrepl/print_method.clj
src/cider/nrepl/version.clj
src/cider_nrepl/plugin.clj

Add clj-kondo

---

project.clj
test/clj/cider/nrepl/middleware/slurp_test.clj
test/clj/cider/nrepl/middleware/stacktrace_test.clj
test/clj/cider/nrepl/middleware/util/instrument_test.clj
test/clj/cider/nrepl/version_test.clj
test/spec/cider/nrepl/middleware/stacktrace_spec_test.clj

https://github.com/jonase/eastwood/blob/master/changes.md#changes-from-0314-to-040

Upgrade and satisfy Eastwood

---

README.md
project.clj
src/cider/nrepl/middleware/complete.clj

Update suitable to 0.4.0, enabling dynamic shadow-cljs code completions.

[chore] update suitable to 0.4.0

---

test/clj/cider/nrepl/middleware/test_test.clj

While working on https://github.com/clojure-emacs/cider-nrepl/pull/701 I almost shipped a bug; the test suite didn't catch it but clj-kondo did.
Which meant we had some missing test coverage for the `stack-trace` functionality.
This PR adds a basic test.

Introduce `deftest stack-frame-test`

---

.circleci/config.yml
project.clj

* Upgrade linters
* Add JDK 16, JDK 17 to the CI matrix

Add JDK 16, JDK 17 to the CI matrix

---

CHANGELOG.md
Makefile
doc/modules/ROOT/pages/nrepl-api/ops.adoc
doc/modules/ROOT/pages/usage.adoc
project.clj
test/clj/cider/nrepl/middleware/info_test.clj

Mainly updates `suitable`, for shipping https://github.com/clojure-emacs/clj-suitable/issues/22
@bbatsov : please let's cut a minor release with this one 🙏

Upgrade some dependencies

---

.circleci/config.yml
.circleci/deploy/deploy_release.clj
Makefile
README.md
project.clj
resources/cider/nrepl/version.edn
src/cider/nrepl/version.clj

Modeled after https://github.com/clojure-emacs/refactor-nrepl/pull/360 + https://github.com/clojure-emacs/refactor-nrepl/pull/362

Setup deployments in CI

---

CHANGELOG.md
project.clj

https://github.com/clojure-emacs/orchard/blob/v0.9.2/CHANGELOG.md#092-2022-02-22

v0.28.3 / Upgrade Orchard

---

test/clj/cider/nrepl/middleware/inspect_test.clj
test/cljs/cider/nrepl/middleware/cljs_inspect_test.clj
test/smoketest/project.clj

Update the inspect test data to match the new section headers and the
Datafy support added to Orchard.

Fix inspect tests

---

CHANGELOG.md
project.clj

https://github.com/alexander-yakushev/compliment/blob/0.4.0/CHANGELOG.md#040-2023-07-05

Bump compliment to 0.4.0

---

CHANGELOG.md
doc/modules/ROOT/pages/nrepl-api/ops.adoc
project.clj
src/cider/nrepl.clj
src/cider/nrepl/middleware/xref.clj
test/clj/cider/nrepl/middleware/xref_test.clj

Fixes https://github.com/clojure-emacs/cider-nrepl/issues/796
Cheers - V

`fn-refs` and `fn-deps` middleware: offer `file-url` field

---

CHANGELOG.md
Makefile
README.md
doc/modules/ROOT/pages/usage.adoc
project.clj

Bump Haystack

---

CHANGELOG.md
Makefile
README.md
doc/modules/ROOT/pages/usage.adoc
project.clj

https://github.com/clojure-emacs/haystack/blob/0077b5c49f4aef1c7f89d5430d6dda2f9e7d78d4/CHANGELOG.md#020-2023-08-20
https://clojars.org/mx.cider/haystack/versions/0.2.0

Use Haystack 0.2.0

---

CHANGELOG.md
Makefile
README.md
doc/modules/ROOT/pages/usage.adoc
project.clj

Commits:
* Add a Makefile default goal
* This eases local iteration.
* Bump Compliment
* 0.36.1

Bump Compliment

---

CHANGELOG.md
Makefile
README.md
doc/antora.yml
doc/modules/ROOT/pages/nrepl-api/ops.adoc
doc/modules/ROOT/pages/usage.adoc
project.clj
src/cider/nrepl.clj
src/cider/nrepl/middleware/inspect.clj

* Add `inspect-tap-indexed`
* 0.44.0

Add `inspect-tap-indexed`

---

CHANGELOG.md
src/cider/nrepl.clj

See https://github.com/nrepl/nrepl/issues/308

Forcibly exit the JVM on older Clojure versions

---

CHANGELOG.md
doc/modules/ROOT/pages/nrepl-api/ops.adoc
project.clj
src/cider/nrepl.clj
src/cider/nrepl/middleware/info.clj
src/cider/nrepl/middleware/log.clj
test/clj/cider/nrepl/middleware/info_test.clj
test/clj/cider/nrepl/middleware/inspect_test.clj

* Bump [Logjam](https://github.com/clojure-emacs/logjam/blob/v0.3.0/CHANGELOG.md#030-2024-03-03)
* Bump [Orchard](https://github.com/clojure-emacs/orchard/blob/v0.23.0/CHANGELOG.md#0230-2024-03-03)
* `middleware.info`: offer new `var-meta-allowlist` option
* Fixes #851
* Adapt a test to Clojure `master` changes
Cheers - V

middleware.info: offer new `var-meta-allowlist` option

---

Makefile
test/clj/cider/nrepl/middleware/inspect_test.clj
test/clj/cider/nrepl/middleware/util/instrument_test.clj

Adapt `instrument-function-call-test` to Clojure master

---

CHANGELOG.md
project.clj

* Use Orchard 0.23.1
* Use Compliment 0.5.2

Bump Orchard, Compliment

---

CHANGELOG.md
project.clj
src/cider/nrepl/middleware/inspect.clj
test/clj/cider/nrepl/middleware/inspect_test.clj
test/clj/cider/nrepl/middleware/stacktrace_test.clj
test/cljs/cider/nrepl/middleware/cljs_inspect_test.clj

I feel stupid, does bencode support passing boolean false? :)

[inspector] Pass :spacious option to Orchard inspector

---

src/cider/nrepl/middleware/refresh.clj

Follows up https://github.com/clojure-emacs/cider-nrepl/pull/873

Rename a variable

---

CHANGELOG.md
src/cider/nrepl/middleware/macroexpand.clj
test/clj/cider/nrepl/middleware/macroexpand_test.clj

Context: https://clojurians.slack.com/archives/C0617A8PQ/p1725361078656679

[macroexpand] Ensure print mw doesn't interfere with expansion

---

.circleci/config.yml
.clj-kondo/config.edn
CHANGELOG.md
Makefile
README.md
download-jdk-sources.sh
project.clj
src/cider/nrepl/middleware/slurp.clj
test/clj/cider/nrepl/middleware/classpath_test.clj
test/clj/cider/nrepl/middleware/info_test.clj

Bumping Orchard and cleaning up Makefile/CI to be the same as in Orchard (download and repackage JDK sources for each JDK version, etc.).

Bump Orchard

---

CHANGELOG.md
project.clj
src/cider/nrepl.clj

Bump Orchard and protect initialization with try/catch

---

CHANGELOG.md
project.clj
test/clj/cider/nrepl/middleware/complete_test.clj
test/clj/cider/nrepl/middleware/info_test.clj
test/clj/cider/nrepl/middleware/inspect_test.clj
test/clj/cider/nrepl/middleware/test_test.clj
test/clj/cider/test_helpers.clj

A bunch of goodies in the new version.
Some test prettyfication as a bonus.
---

Bump compliment to 0.7.0

---

CHANGELOG.md
doc/modules/ROOT/pages/nrepl-api/ops.adoc
project.clj
src/cider/nrepl.clj
src/cider/nrepl/middleware/inspect.clj
test/clj/cider/nrepl/middleware/inspect_test.clj
test/clj/cider/test_helpers.clj
test/cljs/cider/nrepl/middleware/cljs_inspect_test.clj

Sister PR: https://github.com/clojure-emacs/orchard/pull/329
Nothing very interesting going on here, just proxying.
---

[inspect] Add inspect-show-analytics op

---

CHANGELOG.md
doc/modules/ROOT/pages/nrepl-api/ops.adoc
project.clj
src/cider/nrepl.clj
src/cider/nrepl/middleware/inspect.clj
test/clj/cider/nrepl/middleware/inspect_test.clj
test/clj/cider/nrepl/middleware/profile_test.clj
test/cljs/cider/nrepl/middleware/cljs_inspect_test.clj

[inspect] Add support for sort-maps and diff view
